Repository kubevirt/vm-import-operator, pull requests merged in 2020-05, with the labels that each got.

#171 Use vNIC Profile as source network mappings for oVirt
  README.md
  docs/design.md
  examples/ovirt_resourcemapping_example_cr.yaml
  pkg/apis/v2v/v1alpha1/resourcemapping_types.go
  pkg/providers/ovirt/validation/validators/network-mapping-validator.go
  pkg/providers/ovirt/validation/validators/network-mapping-validator_test.go
  tests/cirros/mapping.yml
Labels: dco-signoff: yes, release-note-none, size/L

#172 Use Vnic Profile as source mapping
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/ovirt/mapper/mapper_test.go
  pkg/providers/ovirt/utils/utils.go
  pkg/providers/ovirt/validation/validators/network-mapping-validator.go
Labels: dco-signoff: yes, release-note-none, size/M

#174 Extracted OS Finder
  pkg/os/os-mapper-provider.go
  pkg/providers/ovirt/os/os-finder.go
  pkg/providers/ovirt/os/os-finder_test.go
  pkg/providers/ovirt/os/os_suite_test.go
  pkg/providers/ovirt/provider.go
  pkg/providers/ovirt/provider_test.go
  pkg/providers/ovirt/templates/template-finder.go
  pkg/providers/ovirt/templates/template-finder_test.go
Labels: dco-signoff: yes, release-note-none, size/L

#170 Networked VM e2e tests
  tests/basic_net_vm_import_test.go
  tests/basic_vm_import_test.go
  tests/matchers/data-volume.go
  tests/utils/utils.go
Labels: dco-signoff: yes, release-note-none, size/L

#175 Adding tablet input device when VNC is enabled
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/ovirt/mapper/mapper_test.go
  pkg/providers/ovirt/provider.go
  tests/basic_vm_import_test.go
  tests/utils/utils.go
Labels: dco-signoff: yes, release-note-none, size/L

#159 Fix path to manifests in tests
  .gitignore
  Makefile
  automation/test.sh
  cluster-sync/clean.sh
  cluster-sync/ephemeral_provider.sh
  cluster-sync/external/README.md
  cluster-sync/external/provider.sh
  cluster-sync/install.sh
  cluster-sync/k8s-1.16.2/provider.sh
  cluster-sync/nfs/nfs-sc.yaml
  cluster-sync/nfs/nfs-server.yaml
  cluster-sync/nfs/nfs-service.yaml
  cluster-sync/ocp-4.3/README.md
  cluster-sync/ocp-4.3/provider.sh
  cluster-sync/sync.sh
  cluster-up/check.sh
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/cluster/external/README.md
  cluster-up/cluster/external/provider.sh
  cluster-up/cluster/images.sh
  cluster-up/cluster/k8s-1.16.2/provider.sh
  cluster-up/cluster/k8s-provider-common.sh
  cluster-up/cluster/local/README.md
  cluster-up/cluster/local/provider.sh
  cluster-up/cluster/ocp-4.3/README.md
  cluster-up/cluster/ocp-4.3/provider.sh
  cluster-up/cluster/openshift-provider-common.sh
  cluster-up/container.sh
  cluster-up/down.sh
  cluster-up/hack/common.key
  cluster-up/hack/common.sh
  cluster-up/hack/config-default.sh
  cluster-up/hack/config.sh
  cluster-up/ssh.sh
  cluster-up/up.sh
  cluster-up/virtctl.sh
  cluster/clean.sh
  cluster/cli.sh
  cluster/common.sh
  cluster/down.sh
  cluster/imageio.yaml
  cluster/kubeconfig.sh
  cluster/kubectl.sh
  cluster/kubevirtci.sh
  cluster/operator-install.sh
  cluster/operator-push.sh
  cluster/up.sh
Labels: dco-signoff: yes, release-note-none, size/XXL

#178 Install fakeovirt and imageio during test
  cluster/up.sh
Labels: dco-signoff: yes, release-note-none, size/XS

#179 Adding owner reference to temporary secret and config map.
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/ownerreferences/ownerreferences.go
  pkg/providers/ovirt/provider.go
  tests/cancel_vm_import_test.go
  tests/framework/cdi.go
  tests/framework/vm-import.go
  tests/framework/vm.go
  tests/matchers/matchers.go
  tests/matchers/vm-import.go
Labels: dco-signoff: yes, release-note-none, size/L

#181 Use master of kubevirtci repo for tests
  cluster/kubevirtci.sh
Labels: dco-signoff: yes, release-note-none, size/XS

#182 Functional testing documentation
  README.md
  docs/functional-tests.md
Labels: dco-signoff: yes, release-note-none, size/M

#185 Remove manifests for an unreleased version
  manifests/vm-import-operator/v0.0.2/config_map.yaml
  manifests/vm-import-operator/v0.0.2/namespace.yaml
  manifests/vm-import-operator/v0.0.2/operator.yaml
  manifests/vm-import-operator/v0.0.2/v2v.kubevirt.io_vmimportconfigs_crd.yaml
  manifests/vm-import-operator/v0.0.2/v2v_v1alpha1_resourcemapping_crd.yaml
  manifests/vm-import-operator/v0.0.2/v2v_v1alpha1_virtualmachineimport_crd.yaml
  manifests/vm-import-operator/v0.0.2/vm-import-operator.0.0.2.clusterserviceversion.yaml
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/XL

#187 Rename kubevirtci cluster as per latest changes
  cluster/kubevirtci.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/XS

#186 Build operator by 'make docker-build'
  Makefile
Labels: dco-signoff: yes, release-note-none, size/XS

#188 add vmimportconfig CRD to generator
  pkg/operator/resources/operator/operator.go
Labels: dco-signoff: yes, release-note-none, size/L

#189 'latest' is not a semver and cannot be used with csv-generator
  cluster/operator-install.sh
  cluster/operator-push.sh
Labels: dco-signoff: yes, release-note-none, size/XS

#184 Add events emitting
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
  pkg/providers/ovirt/provider.go
  pkg/providers/provider.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/M

#190 hco: add vmimport config cr
  manifests/vm-import-operator/v0.0.1/v2v.kubevirt.io_vmimportconfigs_cr.yaml
  templates/vm-import-operator/VERSION/v2v.kubevirt.io_vmimportconfigs_cr.yaml.in
Labels: dco-signoff: yes, release-note-none, size/S

#183 Added NIC failed validation e2e tests
  docs/functional-tests.md
  go.sum
  tests/basic_net_vm_import_test.go
  tests/basic_vm_import_test.go
  tests/matchers/vm-import.go
  tests/network_validation_test.go
Labels: dco-signoff: yes, release-note-none, size/L

#194 hco: add required annotations to ClusterServiceVersion
  pkg/operator/resources/operator/operator.go
Labels: dco-signoff: yes, release-note-none, size/S

#195 Generate CRDs for CSV-Generator
  go.mod
  go.sum
  pkg/apis/v2v/v1alpha1/virtualmachineimport_types.go
  pkg/operator/resources/operator/operator.go
  pkg/operator/resources/operator/operator_suite_test.go
  pkg/operator/resources/operator/operator_test.go
  vendor/github.com/RHsyseng/operator-utils/LICENSE
  vendor/github.com/RHsyseng/operator-utils/pkg/validation/schema.go
  vendor/github.com/RHsyseng/operator-utils/pkg/validation/schema_sync.go
  vendor/modules.txt
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/XXL

#196 Clear whitespaces
  docs/functional-tests.md
Labels: dco-signoff: yes, release-note-none

#193 Resource mapping tests
  docs/functional-tests.md
  tests/basic_net_vm_import_test.go
  tests/basic_vm_import_test.go
  tests/cancel_vm_import_test.go
  tests/framework/resource-mapping.go
  tests/matchers/data-volume.go
  tests/network_validation_test.go
  tests/resource_mapping_test.go
  tests/utils/utils.go
Labels: dco-signoff: yes, release-note-none, size/L

#199 Support variations of the release
  Makefile
  README.md
  hack/release.sh
Labels: dco-signoff: yes, release-note-none, size/M

#198 Allow user to override OS Map
  README.md
  cluster/clean.sh
  cluster/operator-push.sh
  docs/design.md
  examples/config_map.yaml
  pkg/operator/resources/operator/operator.go
  pkg/os/os-mapper-provider.go
  pkg/os/os-mapper-provider_suite_test.go
  pkg/os/os-mapper-provider_test.go
  templates/vm-import-operator/VERSION/operator.yaml.in
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/L

#200 Extend test for os-map-provider
  pkg/os/os-mapper-provider_test.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/XS

#197 Functional tests for VM with more than one disk
  automation/test.sh
  docs/functional-tests.md
  tests/multiple_disks_test.go
Labels: dco-signoff: yes, release-note-none, size/M

#192 Install golang during up.sh
  cluster/common.sh
  cluster/up.sh
Labels: dco-signoff: yes, release-note-none, size/XS

#201 Moved common variables and constants to separate files
  tests/basic_net_vm_import_test.go
  tests/basic_vm_import_test.go
  tests/cancel_vm_import_test.go
  tests/common_test.go
  tests/multiple_disks_test.go
  tests/network_validation_test.go
  tests/ovirt-vms/definitions.go
  tests/resource_mapping_test.go
Labels: dco-signoff: yes, release-note-none, size/L

#202 Add steps for using user OS Map
  docs/design.md
  docs/images/vm-import-operator-deployment.png
  hack/whitespace.sh
Labels: dco-signoff: yes, release-note-none, size/S

#206 Adding k8s.cni.cncf.io/network-attachment-definitions privileges
  manifests/vm-import-operator/v0.0.1/operator.yaml
  pkg/operator/resources/operator/operator.go
  templates/vm-import-operator/VERSION/operator.yaml.in
Labels: dco-signoff: yes, release-note-none, size/M

#208 Use upstream golang in tests
  cluster/common.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/XS

#211 Don't use sudo in test scripts
  cluster/common.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/XS

#204 Update vm import progress reflect dv import
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
Labels: dco-signoff: yes, release-note-none, size/M

#212 Silent the wget output
  automation/test.sh
  cluster/common.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/XS

#210 Add new information events
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
Labels: dco-signoff: yes, release-note-none, size/S

#207 Functional test for VM with multus network
  automation/test.sh
  cluster/common.sh
  cluster/manifests/cnao.yaml
  cluster/manifests/imageio.yaml
  cluster/up.sh
  docs/functional-tests.md
  go.mod
  tests/basic_net_vm_import_test.go
  tests/framework/framework.go
  tests/framework/network-attachment-definition.go
  tests/framework/node.go
  tests/framework/resource-mapping.go
  tests/networking_test.go
  tests/ovirt-vms/definitions.go
Labels: dco-signoff: yes, release-note-none, size/L

#214 Use Virtual Machine Instance's Status.Phase in assertion
  tests/matchers/vmi.go
  tests/networking_test.go
Labels: dco-signoff: yes, release-note-none, size/S

#213 Add variable to change kubevirtci version
  cluster/kubevirtci.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/XS

#215 Don't use depracated runtime/log
  cmd/manager/main.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/ownerreferences/ownerreferences.go
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/ovirt/provider.go
  pkg/providers/ovirt/validation/validators/validator-wrapper.go
  pkg/providers/ovirt/validation/validators/vm-validator.go
  pkg/providers/ovirt/validation/vm-import-validation.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/S

#220 Update operator manual deployment
  Makefile
  hack/generate-manifests.sh
  pkg/operator/resources/operator/operator.go
  templates/vm-import-operator/VERSION/operator.yaml.in
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/M

#219 README: fix tiny typo
  README.md
Labels: dco-signoff: yes, release-note-none, size/XS

#221 Update watched types by vm-import-controller
  cmd/manager/main.go
  pkg/operator/resources/operator/operator.go
  templates/vm-import-operator/VERSION/operator.yaml.in
Labels: dco-signoff: yes, release-note-none, size/S

#222 Use new name format of manifest
  cluster/clean.sh
  cluster/operator-push.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/XS

#224 Move vmimportconfig to operator.yaml
  templates/vm-import-operator/VERSION/operator.yaml.in
  templates/vm-import-operator/VERSION/vmimportconfig_crd.yaml.in
Labels: dco-signoff: yes, release-note-none, size/M

#223 RBAC: fix roles for the controller
  pkg/operator/controller/controller.go
  pkg/operator/resources/operator/operator.go
  templates/vm-import-operator/VERSION/operator.yaml.in
Labels: dco-signoff: yes, release-note-none, size/L

#225 Remove controller CRDs
  templates/vm-import-operator/VERSION/resourcemapping_crd.yaml.in
  templates/vm-import-operator/VERSION/virtualmachineimport_crd.yaml.in
Labels: dco-signoff: yes, release-note-none, size/L

#226 Add missing permissions
  pkg/operator/resources/operator/operator.go
  templates/vm-import-operator/VERSION/operator.yaml.in
Labels: dco-signoff: yes, release-note-none, size/S

#227 deprecate usage of flavor.template.kubevirt.io/Custom label
  pkg/providers/ovirt/mapper/mapper.go
Labels: dco-signoff: yes, release-note-none, size/XS

#228 Remove duplicated policy rule
  pkg/operator/resources/operator/operator.go
Labels: dco-signoff: yes, release-note-none, size/S

#230 fix docs link
  docs/developers.md
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/XS

#229 Set correct ns when creating serviceMonitor
  cmd/manager/main.go
Labels: dco-signoff: yes, release-note-none, size/XS

#231 Remote debugging of controller/operator
  Makefile
  cmd/manager/main.go
  cmd/operator/operator.go
  docs/developers.md
Labels: dco-signoff: yes, release-note-none, size/M

#232 Add status subresource to generated CRDs
  pkg/operator/resources/operator/operator.go
Labels: dco-signoff: yes, release-note-none

#233 Generate controller manifests
  docs/developers.md
  hack/generate-controller-manifests.sh
  tools/csv-generator/csv-generator.go
Labels: dco-signoff: yes, release-note-none, size/M

#235 Add missing permission
  pkg/operator/resources/operator/operator.go
Labels: dco-signoff: yes, do-not-merge/hold, release-note-none, size/S

#236 Move missing permission from operator to controller
  pkg/operator/resources/operator/operator.go
Labels: dco-signoff: yes, release-note-none, size/S

#237 Update CRD to the latest version
  pkg/operator/controller/controller.go
  pkg/operator/resources/operator/operator.go
  templates/vm-import-operator/VERSION/operator.yaml.in
Labels: dco-signoff: yes, release-note-none, size/M

#234 Use new CR for tests
  cluster/clean.sh
  cluster/operator-install.sh
  cluster/operator-push.sh
Labels: dco-signoff: yes, release-note-none, size/S

#239 Change update to patch for VMImportConfig.Status
  pkg/operator/controller/controller.go
Labels: dco-signoff: yes, release-note-none, size/S

#240 Release v0.0.2
  Makefile
  README.md
  manifests/vm-import-operator/v0.0.2/namespace.yaml
  manifests/vm-import-operator/v0.0.2/operator.yaml
  manifests/vm-import-operator/v0.0.2/vm-import-operator.0.0.2.clusterserviceversion.yaml
  manifests/vm-import-operator/v0.0.2/vmimportconfig_cr.yaml
  version/description
  version/version.go
Labels: dco-signoff: yes, release-note-none, size/XL

#241 Update owned CRD in CSV
  pkg/operator/resources/operator/operator.go
Labels: dco-signoff: yes, do-not-merge/hold, release-note-none, size/XS

#242 Watch for failures of the disk import
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
  pkg/datavolumes/datavolumes.go
  pkg/providers/ovirt/provider.go
  pkg/providers/provider.go
  pkg/virtualmachines/virtualmachines.go
Labels: dco-signoff: yes, release-note-none, size/L

#246 Guidelines
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  docs/developers.md
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/L

#249 Taking into account eventual consistency for dependencies removal
  tests/cancel_vm_import_test.go
  tests/framework/vm.go
Labels: dco-signoff: yes, release-note-none, size/M

#248 Fixed some typos
  CONTRIBUTING.md
Labels: dco-signoff: yes, release-note-none, size/S

#247 Functional tests for VM validation
  cluster/common.sh
  docs/functional-tests.md
  go.mod
  go.sum
  tests/framework/framework.go
  tests/framework/stubbing.go
  tests/ovirt-vms/definitions.go
  tests/stubbing/disk-attachments.xml
  tests/stubbing/disk.xml
  tests/stubbing/graphic-consoles-empty.xml
  tests/stubbing/invalid/diag288-watchdog.xml
  tests/stubbing/invalid/illegal-images-vm.xml
  tests/stubbing/invalid/kubevirt-origin-vm.xml
  tests/stubbing/invalid/migratable-placement-policy-affinity-vm.xml
  tests/stubbing/invalid/unsupported-diag288-watchdog-vm.xml
  tests/stubbing/invalid/unsupported-i440fx_sea_bios-bios-type-vm.xml
  tests/stubbing/invalid/unsupported-s390x-architecture-vm.xml
  tests/stubbing/invalid/unsupported-status-vm-template.xml
  tests/stubbing/invalid/usb-enabled-vm.xml
  tests/stubbing/nics-empty.xml
  tests/stubbing/storage-domain.xml
  tests/vm_validation_test.go
  vendor/github.com/gorilla/mux/.travis.yml
  vendor/github.com/gorilla/mux/ISSUE_TEMPLATE.md
  vendor/github.com/gorilla/mux/README.md
  vendor/github.com/gorilla/mux/context.go
  vendor/github.com/gorilla/mux/doc.go
  vendor/github.com/gorilla/mux/go.mod
  vendor/github.com/gorilla/mux/middleware.go
  vendor/github.com/gorilla/mux/mux.go
  vendor/github.com/gorilla/mux/regexp.go
  vendor/github.com/gorilla/mux/route.go
  vendor/github.com/gorilla/mux/test_helpers.go
  vendor/github.com/machacekondra/fakeovirt/pkg/api/stubbing/stubbing-builder.go
  vendor/github.com/machacekondra/fakeovirt/pkg/api/stubbing/stubbing.go
  vendor/github.com/machacekondra/fakeovirt/pkg/client/fakeovirt-client.go
  vendor/modules.txt
Labels: dco-signoff: yes, release-note-none, size/XXL

#250 Networking tests
  docs/functional-tests.md
  tests/networking_test.go
  tests/ovirt-vms/definitions.go
  tests/stubbing/networks/net-1.xml
  tests/stubbing/networks/net-2.xml
  tests/stubbing/nics-one.xml
  tests/stubbing/nics-two.xml
  tests/stubbing/vms/basic-vm.xml
  tests/stubbing/vms/two-networks-vm.xml
  tests/stubbing/vnic_profiles/vnic-profile-1.xml
  tests/stubbing/vnic_profiles/vnic-profile-2.xml
Labels: dco-signoff: yes, release-note-none, size/L

#251 VM Storage validation functional tests
  docs/functional-tests.md
  tests/networking_test.go
  tests/ovirt-vms/definitions.go
  tests/storage_validation_test.go
  tests/stubbing/disk-attachments/interface-template.xml
  tests/stubbing/disk-attachments/one-attachment.xml
  tests/stubbing/disks/disk-1.xml
  tests/stubbing/disks/interface-template.xml
  tests/stubbing/disks/sgio-template.xml
  tests/stubbing/disks/status-template.xml
  tests/stubbing/disks/storage-type-template.xml
  tests/stubbing/invalid/disk-attachments/disk-attachments-empty.xml
  tests/stubbing/invalid/disk-attachments/scsi-reservation.xml
  tests/stubbing/invalid/disks/lun-storage.xml
  tests/stubbing/invalid/disks/scsi-reservation.xml
  tests/stubbing/vms/basic-vm.xml
  tests/vm_validation_test.go
Labels: dco-signoff: yes, release-note-none, size/L

#253 Update network mapping value for ovirt
  docs/design.md
  examples/ovirt_resourcemapping_example_cr.yaml
  examples/ovirt_virtualmachineimport_example_cr.yaml
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/S

#252 e2e ovirt-related tests separation
  automation/test.sh
  tests/common-vars.go
  tests/common_test.go
  tests/ovirt/basic_net_vm_import_test.go
  tests/ovirt/basic_vm_import_test.go
  tests/ovirt/cancel_vm_import_test.go
  tests/ovirt/multiple_disks_test.go
  tests/ovirt/network_validation_test.go
  tests/ovirt/networking_test.go
  tests/ovirt/resource_mapping_test.go
  tests/ovirt/storage_validation_test.go
  tests/ovirt/stubbing/disk-attachments/interface-template.xml
  tests/ovirt/stubbing/disk-attachments/one-attachment.xml
  tests/ovirt/stubbing/disks/disk-1.xml
  tests/ovirt/stubbing/disks/interface-template.xml
  tests/ovirt/stubbing/disks/sgio-template.xml
  tests/ovirt/stubbing/disks/status-template.xml
  tests/ovirt/stubbing/disks/storage-type-template.xml
  tests/ovirt/stubbing/graphic-consoles-empty.xml
  tests/ovirt/stubbing/invalid/diag288-watchdog.xml
  tests/ovirt/stubbing/invalid/disk-attachments/disk-attachments-empty.xml
  tests/ovirt/stubbing/invalid/disk-attachments/scsi-reservation.xml
  tests/ovirt/stubbing/invalid/disks/lun-storage.xml
  tests/ovirt/stubbing/invalid/disks/scsi-reservation.xml
  tests/ovirt/stubbing/invalid/illegal-images-vm.xml
  tests/ovirt/stubbing/invalid/kubevirt-origin-vm.xml
  tests/ovirt/stubbing/invalid/migratable-placement-policy-affinity-vm.xml
  tests/ovirt/stubbing/invalid/unsupported-diag288-watchdog-vm.xml
  tests/ovirt/stubbing/invalid/unsupported-i440fx_sea_bios-bios-type-vm.xml
  tests/ovirt/stubbing/invalid/unsupported-s390x-architecture-vm.xml
  tests/ovirt/stubbing/invalid/unsupported-status-vm-template.xml
  tests/ovirt/stubbing/invalid/usb-enabled-vm.xml
  tests/ovirt/stubbing/networks/net-1.xml
  tests/ovirt/stubbing/networks/net-2.xml
  tests/ovirt/stubbing/nics-empty.xml
  tests/ovirt/stubbing/nics-one.xml
  tests/ovirt/stubbing/nics-two.xml
  tests/ovirt/stubbing/storage-domain.xml
  tests/ovirt/stubbing/vms/basic-vm.xml
  tests/ovirt/stubbing/vms/two-networks-vm.xml
  tests/ovirt/stubbing/vnic_profiles/vnic-profile-1.xml
  tests/ovirt/stubbing/vnic_profiles/vnic-profile-2.xml
  tests/ovirt/tests_suite_test.go
  tests/ovirt/vm_validation_test.go
  tests/ovirt/vms/definitions.go
Labels: dco-signoff: yes, release-note-none, size/L

#256 Add IMPORT_POD_RESTART_TOLERANCE env var
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/operator/resources/operator/operator.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/S

#259 Defined new VM configuration-related e2e test cases
  docs/functional-tests.md
Labels: dco-signoff: yes, release-note, size/S

#258 Add vm description
  examples/ovirt_virtualmachineimport_example_cr.yaml
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
  pkg/operator/resources/operator/operator.go
  pkg/utils/utils.go
Labels: dco-signoff: yes, release-note-none, size/M

#261 Reduce restrictions on targer in mappings
  pkg/operator/resources/operator/operator.go
Labels: dco-signoff: yes, release-note-none, size/XS

#262 Bump default k8s version to 1.18
  automation/test.sh
  cluster/common.sh
  cluster/kubevirtci.sh
  cluster/up.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/S

#260 Timezone validation e2e tests and fix
  build/controller/Dockerfile
  docs/functional-tests.md
  pkg/providers/ovirt/validation/vm-import-validation.go
  pkg/providers/ovirt/validation/vm-import-validation_test.go
  tests/ovirt/stubbing/invalid/disk-attachments/scsi-reservation.xml
  tests/ovirt/stubbing/vms/timezone-template.xml
  tests/ovirt/various_vm_configurations_test.go
  tests/ovirt/vm_validation_test.go
  tests/ovirt/vms/definitions.go
Labels: dco-signoff: yes, release-note, size/L

#263 Functional tests for invalid image
  docs/functional-tests.md
  tests/framework/vm-import.go
  tests/matchers/vm-import.go
  tests/ovirt/basic_vm_import_negative_test.go
  tests/ovirt/stubbing/disk-attachments/invalid-disk.xml
  tests/ovirt/stubbing/disks/invalid-disk.xml
  tests/ovirt/stubbing/vms/invalid-disk.xml
  tests/ovirt/vms/definitions.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/L
