Repository kubevirt/vm-import-operator, pull requests merged in 2020-07, with the labels that each got.

#314 Add nfs storage to automation
  cluster/common.sh
  cluster/manifests/nfs/nfs-sc.yaml
  cluster/manifests/nfs/nfs-server.yaml
  cluster/manifests/nfs/nfs-service.yaml
  cluster/up.sh
  tests/framework/framework.go
  tests/ovirt/various_vm_configurations_test.go
  tests/ovirt/vms/definitions.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/L

#320 Using kubevirt install namespace passed in the test run arguments.
  tests/ovirt/basic_vm_import_negative_test.go
  tests/ovirt/various_vm_configurations_test.go
Labels: dco-signoff: yes, release-note-none, size/S

#321 Allow user to specify storage classes for tests
  tests/common-vars.go
  tests/framework/framework.go
  tests/ovirt/basic_vm_import_test.go
  tests/ovirt/resource_mapping_test.go
  tests/ovirt/various_vm_configurations_test.go
  tests/ovirt/vms/definitions.go
Labels: dco-signoff: yes, release-note, size/M

#310 Do not requeue new request if provider init failed
  go.mod
  go.sum
  pkg/apis/v2v/v1alpha1/virtualmachineimport_types.go
  pkg/client/client.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
  pkg/providers/ovirt/client/ovirt-client.go
  pkg/providers/ovirt/provider.go
  pkg/providers/provider.go
  tests/matchers/vm-import.go
  tests/ovirt/basic_vm_import_negative_test.go
  tests/ovirt/multiple_vms_import_test.go
  vendor/github.com/ovirt/go-ovirt/connection.go
  vendor/modules.txt
Labels: dco-signoff: yes, release-note-none, size/L

#324 Release v0.0.4
  Makefile
  README.md
  manifests/vm-import-operator/v0.0.4/namespace.yaml
  manifests/vm-import-operator/v0.0.4/operator.yaml
  manifests/vm-import-operator/v0.0.4/vm-import-operator.0.0.4.clusterserviceversion.yaml
  manifests/vm-import-operator/v0.0.4/vmimportconfig_cr.yaml
  version/description
  version/version.go
Labels: dco-signoff: yes, release-note-none, size/L

#326 Updated v0.0.4 images
  manifests/vm-import-operator/v0.0.4/operator.yaml
  manifests/vm-import-operator/v0.0.4/vm-import-operator.0.0.4.clusterserviceversion.yaml
Labels: dco-signoff: yes, release-note-none, size/XS

#327 Functional tests little fixes
  automation/execute-tests.sh
  tests/env/ovirt/ovirt.go
  tests/framework/framework.go
  tests/matchers/vmi.go
  tests/ovirt/basic_vm_import_test.go
Labels: dco-signoff: yes, release-note-none, size/S

#329 Fix element networkMapping in example
  examples/ovirt/vmimport-external-mapping.yaml
  examples/ovirt/vmimport-internal-mapping.yaml
Labels: dco-signoff: yes, release-note-none, size/XS

#323 Restore source vm status when import cancelled
  go.mod
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
  pkg/providers/ovirt/provider.go
  pkg/providers/provider.go
  pkg/utils/utils.go
Labels: dco-signoff: yes, release-note-none, size/L

#334 Use kubevirt version v0.30.3 in automation
  cluster/common.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/XS

#331 Add debug to ovirt client
  pkg/providers/ovirt/client/ovirt-client.go
Labels: dco-signoff: yes, release-note-none, size/S

#328 Add metric kubevirt_vmimport
  cluster/operator-install.sh
  cmd/manager/main.go
  cmd/operator/operator.go
  docs/metrics.md
  go.mod
  go.sum
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/metrics/metrics.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_test.go
  pkg/operator/resources/operator/operator.go
  templates/vm-import-operator/VERSION/operator.yaml.in
Labels: dco-signoff: yes, release-note-none, size/L

#338 Fix func tests for kubevirt v0.30.4
  cluster/common.sh
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/ovirt/mapper/mapper_test.go
Labels: dco-signoff: yes, release-note-none, size/M

#339 Release v0.1.0
  Makefile
  README.md
  cluster/common.sh
  manifests/vm-import-operator/v0.1.0/namespace.yaml
  manifests/vm-import-operator/v0.1.0/operator.yaml
  manifests/vm-import-operator/v0.1.0/vm-import-operator.0.1.0.clusterserviceversion.yaml
  manifests/vm-import-operator/v0.1.0/vmimportconfig_cr.yaml
  version/description
  version/version.go
Labels: dco-signoff: yes, release-note-none, size/L

#340 Fix CDI negative disk size test
  cluster/common.sh
  tests/ovirt/basic_vm_import_negative_test.go
Labels: dco-signoff: yes, release-note-none, size/XS

#342 Add reason of timeout error to tests
  pkg/apis/v2v/v1alpha1/virtualmachineimport_types.go
  tests/framework/framework.go
  tests/framework/vm-import.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/S

#341 Target VM name length-related changes
  docs/functional-tests.md
  go.mod
  go.sum
  pkg/configmaps/configmaps.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
  pkg/operator/resources/operator/operator.go
  pkg/providers/ovirt/mapper/mapper.go
  pkg/secrets/secrets.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
  tests/ovirt/basic_vm_import_negative_test.go
  tests/ovirt/cancel_vm_import_test.go
  tests/ovirt/various_vm_configurations_test.go
Labels: dco-signoff: yes, release-note-none, size/L

#348 Target VM name length limit et. al. backport to 0.1.x line
  pkg/configmaps/configmaps.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
  pkg/operator/resources/operator/operator.go
  pkg/providers/ovirt/mapper/mapper.go
  pkg/secrets/secrets.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
  tests/ovirt/basic_vm_import_negative_test.go
  tests/ovirt/cancel_vm_import_test.go
  tests/ovirt/various_vm_configurations_test.go
Labels: dco-signoff: yes, release-note-none, size/L

#350 Check if CRD have stuctural schema
  cluster/common.sh
  cluster/up.sh
Labels: dco-signoff: yes, release-note-none, size/S

#347 Add support for block volumes
  cluster/common.sh
  cluster/up.sh
  pkg/apis/v2v/v1alpha1/resourcemapping_types.go
  pkg/apis/v2v/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/resources/operator/operator.go
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/ovirt/mapper/mapper_test.go
  pkg/providers/ovirt/mappings/merger.go
  pkg/providers/ovirt/mappings/merger_test.go
  pkg/providers/ovirt/validation/mocks_test.go
  pkg/providers/ovirt/validation/validators/network-mapping-validator.go
  pkg/providers/ovirt/validation/validators/network-mapping-validator_test.go
  pkg/providers/ovirt/validation/validators/storage-mapping-validator.go
  pkg/providers/ovirt/validation/validators/storage-mapping-validator_test.go
  pkg/providers/ovirt/validation/validators/validator-wrapper.go
  pkg/providers/ovirt/validation/vm-import-validation.go
  pkg/providers/ovirt/validation/vm-import-validation_test.go
  pkg/utils/utils.go
  tests/ovirt/basic_net_vm_import_test.go
  tests/ovirt/basic_vm_import_negative_test.go
  tests/ovirt/basic_vm_import_test.go
  tests/ovirt/multiple_vms_import_test.go
  tests/ovirt/network_validation_test.go
  tests/ovirt/networking_test.go
  tests/ovirt/resource_mapping_test.go
  tests/ovirt/resource_mapping_validation_test.go
  tests/ovirt/various_vm_configurations_test.go
Labels: dco-signoff: yes, release-note-none, size/XL

#346 Using JSON Patch for updating conditions
  pkg/apis/v2v/v1alpha1/virtualmachineimport_types.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
  tests/ovirt/basic_vm_import_negative_test.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/M

#353 Add description to all fields of our CRDs
  pkg/operator/resources/operator/operator.go
  templates/vm-import-operator/VERSION/operator.yaml.in
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/M

#355 Reformatted VMware client package
  pkg/providers/vmware/client/client.go
  pkg/providers/vmware/client/client_suite_test.go
  pkg/providers/vmware/client/client_test.go
Labels: dco-signoff: yes, release-note, size/S

#354 Add Valid condition warning when default storage class is about to be used
  pkg/apis/v2v/v1beta1/virtualmachineimport_types.go
  pkg/providers/ovirt/validation/validators/definitions.go
  pkg/providers/ovirt/validation/validators/storage-mapping-validator.go
  pkg/providers/ovirt/validation/validators/storage-mapping-validator_test.go
  pkg/providers/ovirt/validation/vm-import-validation.go
  pkg/providers/ovirt/validation/vm-import-validation_test.go
  tests/ovirt/basic_vm_import_test.go
Labels: dco-signoff: yes, release-note-none, size/L
