Repository kubevirt/vm-import-operator, pull requests merged in 2020-10, with the labels that each got.

#408 New metric counter for cancelled imports
  docs/metrics.md
  go.mod
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
  pkg/metrics/metrics.go
  pkg/utils/utils.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, ok-to-test, size/L

#412 Use template validation rules
  pkg/providers/ovirt/validation/validators/vm-validator.go
  pkg/providers/ovirt/validation/validators/vm-validator_test.go
Labels: dco-signoff: yes, release-note-none, size/M

#413 Update placement types
  pkg/operator/resources/operator/operator.go
Labels: dco-signoff: yes, release-note-none, size/XL

#415 Release v0.2.3
  Makefile
  README.md
  manifests/vm-import-operator/v0.2.3/namespace.yaml
  manifests/vm-import-operator/v0.2.3/operator.yaml
  manifests/vm-import-operator/v0.2.3/vm-import-operator.0.2.3.clusterserviceversion.yaml
  manifests/vm-import-operator/v0.2.3/vmimportconfig_cr.yaml
  version/description
  version/version.go
Labels: dco-signoff: yes, release-note, size/L

#416 vSphere: Implement Close() to log out and shutdown idle connections
  pkg/providers/vmware/client/client.go
  pkg/providers/vmware/provider.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/S

#417 Add missing condition
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  tests/framework/vm-import.go
  tests/ovirt/basic_net_vm_import_test.go
  tests/ovirt/basic_vm_import_negative_test.go
  tests/ovirt/basic_vm_import_test.go
  tests/ovirt/cancel_vm_import_test.go
  tests/ovirt/multiple_disks_test.go
  tests/ovirt/multiple_vms_import_test.go
  tests/ovirt/network_validation_test.go
  tests/ovirt/networking_test.go
  tests/ovirt/resource_mapping_test.go
  tests/ovirt/resource_mapping_validation_test.go
  tests/ovirt/storage_validation_test.go
  tests/ovirt/various_vm_configurations_test.go
  tests/ovirt/vm_validation_test.go
Labels: dco-signoff: yes, release-note-none, size/M

#419 Do not override machine type for i440fx
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/ovirt/mapper/mapper_test.go
  pkg/providers/ovirt/validation/validators/definitions.go
  pkg/providers/ovirt/validation/validators/vm-validator.go
  pkg/providers/ovirt/validation/validators/vm-validator_test.go
  pkg/providers/ovirt/validation/vm-import-validation.go
Labels: dco-signoff: yes, release-note-none, size/M

#418 Use label normalizer
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/ovirt/mapper/mapper_test.go
  pkg/utils/utils.go
Labels: dco-signoff: yes, release-note-none, size/M

#414 New metric for import duration (histogram).
  docs/metrics.md
  go.sum
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
  pkg/metrics/metrics.go
Labels: dco-signoff: yes, ok-to-test, release-note-none, size/L

#420 Release v0.2.4
  Makefile
  README.md
  manifests/vm-import-operator/v0.2.4/namespace.yaml
  manifests/vm-import-operator/v0.2.4/operator.yaml
  manifests/vm-import-operator/v0.2.4/vm-import-operator.0.2.4.clusterserviceversion.yaml
  manifests/vm-import-operator/v0.2.4/vmimportconfig_cr.yaml
  version/description
  version/version.go
Labels: dco-signoff: yes, release-note, size/L

#425 Install the latest version of CDI on the test cluster
  cluster/common.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/XS

#426 Use DeletePropagationForeground when deleting jobs
  pkg/jobs/jobs.go
  tests/vmware/basic_vm_import_test.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/S

#422 Expose /dev/kvm in the guest conversion pod
  pkg/guestconversion/guestconversion.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/S

#427 Release v0.2.5
  Makefile
  README.md
  manifests/vm-import-operator/v0.2.5/namespace.yaml
  manifests/vm-import-operator/v0.2.5/operator.yaml
  manifests/vm-import-operator/v0.2.5/vm-import-operator.0.2.5.clusterserviceversion.yaml
  manifests/vm-import-operator/v0.2.5/vmimportconfig_cr.yaml
  version/description
  version/version.go
Labels: dco-signoff: yes, release-note, size/L

#429 vSphere: always map machine type to q35
  pkg/providers/vmware/mapper/mapper.go
  pkg/providers/vmware/mapper/mapper_test.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/S

#428 vSphere: FindTemplate should search for a desktop template if no server templates are found
  pkg/providers/vmware/provider_test.go
  pkg/providers/vmware/templates/template-finder.go
  pkg/providers/vmware/templates/template-finder_test.go
Labels: dco-signoff: yes, release-note-none, size/L
