Repository kubevirt/vm-import-operator, pull requests merged in 2020-08, with the labels that each got.

#357 Config-map based controller configuration
  cmd/manager/main.go
  pkg/config/base-config.go
  pkg/config/controller/config-provider.go
  pkg/config/controller/config.go
  pkg/config/controller/config_test.go
  pkg/config/controller/controller-config_suite_test.go
  pkg/config/kubevirt-config-provider.go
  pkg/config/kubevirt/config-provider.go
  pkg/config/kubevirt/config.go
  pkg/config/kubevirt/config_test.go
  pkg/config/kubevirt/kubevirt-config_suite_test.go
  pkg/controller/controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
  pkg/providers/ovirt/provider.go
  pkg/providers/ovirt/validation/validators/validator-wrapper.go
  pkg/providers/ovirt/validation/validators/vm-validator.go
  pkg/providers/ovirt/validation/validators/vm-validator_test.go
Labels: dco-signoff: yes, release-note, size/L

#349 Add Vmware import source and resource mapping types
  docs/design.md
  examples/vmware/resource_mapping.yaml
  examples/vmware/secret.yaml
  examples/vmware/vmimport-external-mapping.yaml
  examples/vmware/vmimport-internal-mapping.yaml
  pkg/apis/v2v/v1beta1/resourcemapping_types.go
  pkg/apis/v2v/v1beta1/virtualmachineimport_types.go
  pkg/apis/v2v/v1beta1/zz_generated.deepcopy.go
  pkg/operator/resources/operator/operator.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, needs-ok-to-test, size/XL

#361 Remove trailing space from doc
  docs/design.md
Labels: dco-signoff: yes, release-note-none, size/XS

#359 Enable SRIOV
  go.mod
  go.sum
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/ovirt/mapper/mapper_test.go
  pkg/providers/ovirt/utils/utils.go
  pkg/providers/ovirt/validation/validators/definitions.go
  pkg/providers/ovirt/validation/validators/network-mapping-validator.go
  pkg/providers/ovirt/validation/validators/network-mapping-validator_test.go
  pkg/providers/ovirt/validation/validators/nic-validator.go
  pkg/providers/ovirt/validation/validators/nic-validator_test.go
  pkg/providers/ovirt/validation/vm-import-validation.go
  pkg/providers/ovirt/validation/vm-import-validation_test.go
  tests/matchers/vm-import.go
  tests/ovirt/network_validation_test.go
  tests/ovirt/stubbing/vnic-profiles/pass-through.xml
Labels: dco-signoff: yes, release-note-none, size/L

#360 Add pending condition
  go.mod
  go.sum
  pkg/apis/v2v/v1beta1/virtualmachineimport_types.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
Labels: dco-signoff: yes, release-note-none, size/M

#363 Update validation rules
  docs/rules.md
Labels: dco-signoff: yes, release-note-none, size/S

#365 Add v1alpha1 version
  pkg/operator/resources/operator/operator.go
Labels: dco-signoff: yes, release-note-none, size/L

#358 Controller config map backed os mapping
  automation/execute-tests.sh
  cluster/operator-install.sh
  docs/design.md
  docs/functional-tests.md
  docs/images/controller_config_map.png
  docs/images/vm-import-operator-deployment.png
  pkg/config/controller/config-provider.go
  pkg/config/controller/config.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_test.go
  pkg/operator/resources/operator/operator.go
  pkg/os/os-mapper-provider.go
  pkg/os/os-mapper-provider_test.go
  pkg/providers/ovirt/provider.go
  templates/vm-import-operator/VERSION/operator.yaml.in
  tests/os-mapping/operator.yaml.patch
  tests/os-mapping/os-mapping.yaml
  tests/ovirt/user_provided_os_maps_migration_test.go
Labels: dco-signoff: yes, release-note, size/L

#364 Allow to import vms using i440fx bios
  docs/rules.md
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/ovirt/validation/validators/vm-validator_test.go
  tests/ovirt/various_vm_configurations_test.go
  tests/ovirt/vm_validation_test.go
  tests/ovirt/vms/definitions.go
Labels: dco-signoff: yes, do-not-merge/hold, release-note-none, size/S

#367 Add event on import pod failure
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
Labels: dco-signoff: yes, release-note-none, size/XS

#368 Select newest template
  pkg/providers/ovirt/templates/template-finder.go
  pkg/providers/ovirt/templates/template-finder_test.go
Labels: dco-signoff: yes, release-note-none, size/S

#369 Add vSphere OSFinder and GuestOs identifier mappings
  pkg/os/os-mapper-provider.go
  pkg/providers/vmware/os/os-finder.go
  pkg/providers/vmware/os/os-finder_test.go
  pkg/providers/vmware/os/os_suite_test.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/L

#370 Release v0.2.0
  Makefile
  README.md
  manifests/vm-import-operator/v0.2.0/namespace.yaml
  manifests/vm-import-operator/v0.2.0/operator.yaml
  manifests/vm-import-operator/v0.2.0/vm-import-operator.0.2.0.clusterserviceversion.yaml
  manifests/vm-import-operator/v0.2.0/vmimportconfig_cr.yaml
  version/description
  version/version.go
Labels: dco-signoff: yes, release-note-none, size/L

#371 Add TemplateFinder for vSphere provider
  pkg/providers/vmware/templates/template-finder.go
  pkg/providers/vmware/templates/template-finder_test.go
  pkg/providers/vmware/templates/templates_suite_test.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/L

#372 Refactor shared *Manager interfaces into provider package
  pkg/providers/ovirt/provider.go
  pkg/providers/provider.go
Labels: dco-signoff: yes, release-note-none, size/M

#373 Restore v1alpha1 types
  pkg/api-client/clientset/versioned/typed/v2v/v1alpha1/doc.go
  pkg/api-client/clientset/versioned/typed/v2v/v1alpha1/generated_expansion.go
  pkg/api-client/clientset/versioned/typed/v2v/v1alpha1/resourcemapping.go
  pkg/api-client/clientset/versioned/typed/v2v/v1alpha1/v2v_client.go
  pkg/api-client/clientset/versioned/typed/v2v/v1alpha1/virtualmachineimport.go
  pkg/apis/v2v/v1alpha1/doc.go
  pkg/apis/v2v/v1alpha1/register.go
  pkg/apis/v2v/v1alpha1/resourcemapping_types.go
  pkg/apis/v2v/v1alpha1/virtualmachineimport_types.go
  pkg/apis/v2v/v1alpha1/vmimportconfig_types.go
  pkg/apis/v2v/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/v2v/v1alpha1/zz_generated.openapi.go
Labels: dco-signoff: yes, release-note-none, size/XXL

#376 Add virt-v2v container image
  build/virt-v2v/Dockerfile
  build/virt-v2v/bin/entrypoint
Labels: dco-signoff: yes, needs-ok-to-test, release-note, size/M

#378 Update types
  pkg/operator/resources/operator/operator.go
Labels: dco-signoff: yes, release-note-none, size/L

#379 Fix search pattern for qcow2 overlays
  build/virt-v2v/bin/entrypoint
Labels: dco-signoff: yes, needs-ok-to-test, release-note-none, size/XS

#383 Permissions issue during HCO deployment
  pkg/operator/resources/operator/operator.go
Labels: dco-signoff: yes, release-note-none, size/XS

#384 Missing permission
  pkg/operator/resources/operator/operator.go
Labels: dco-signoff: yes, release-note-none, size/S

#386 Add monitoring ns to operator env
  pkg/operator/resources/operator/operator.go
Labels: dco-signoff: yes, release-note-none, size/XS

#385 Allow to watch and create servicemonitors
  pkg/operator/resources/operator/operator.go
Labels: dco-signoff: yes, release-note-none, size/XS

#387 Update older version of VMImportConfig params
  pkg/operator/resources/operator/operator.go
Labels: dco-signoff: yes, release-note-none, size/XS
