Repository kubevirt/vm-import-operator, pull requests merged in 2020-11, with the labels that each got.

#435 Add vSphere resource mapping documentation.
  docs/design.md
  examples/vmware/secret.yaml
  examples/vmware/vmimport-external-mapping.yaml
  examples/vmware/vmimport-internal-mapping.yaml
Labels: dco-signoff: yes, release-note-none, size/M

#432 Add CreateVMSnapshot to Provider interface
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
  pkg/providers/ovirt/provider.go
  pkg/providers/provider.go
  pkg/providers/vmware/client/client.go
  pkg/providers/vmware/client/client_test.go
  pkg/providers/vmware/provider.go
  pkg/providers/vmware/provider_test.go
Labels: dco-signoff: yes, release-note-none, size/L

#439 Fix typo in VM validation for NUMA
  pkg/providers/ovirt/validation/validators/vm-validator.go
Labels: dco-signoff: yes, release-note-none, size/XS

#440 Update oVirt mapping example with volumeMode
  docs/design.md
Labels: dco-signoff: yes, documentation, release-note-none, size/XS

#441 Fix vSphere VM network mapping bugs and misleading error messages
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/providers/vmware/mapper/mapper.go
  pkg/providers/vmware/mapper/mapper_test.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/M

#438 Add optional AccessMode to StorageResourceMappingItem
  go.sum
  pkg/apis/v2v/v1beta1/resourcemapping_types.go
  pkg/apis/v2v/v1beta1/zz_generated.deepcopy.go
  pkg/jobs/jobs.go
  pkg/operator/resources/operator/operator.go
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/vmware/mapper/mapper.go
  pkg/providers/vmware/mapper/mapper_test.go
  pkg/providers/vmware/provider_test.go
  pkg/providers/vmware/templates/template-finder.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/L
