Repository kubevirt/vm-import-operator, pull requests merged in 2020-04, with the labels that each got.

#30 Validation status management refactor
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/providers/ovirt/provider.go
  pkg/providers/ovirt/validation/mocks_test.go
  pkg/providers/ovirt/validation/vm-import-validation.go
  pkg/providers/ovirt/validation/vm-import-validation_test.go
  pkg/providers/provider.go
  pkg/utils/utils.go
Labels: dco-signoff: yes, size/L

#36 Mapping package tests using public API
  pkg/providers/ovirt/mappings/merger_test.go
Labels: dco-signoff: yes, size/M

#37 Ignoring Idea project dir
  .gitignore
Labels: dco-signoff: yes, size/XS

#34 Map VM attributes
  pkg/providers/ovirt/client/ovirt-client.go
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/ovirt/mapper/mapper_test.go
  pkg/providers/ovirt/validation/validators/vm-validator.go
Labels: dco-signoff: yes, size/L

#40 Nic mappings
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/ovirt/mapper/mapper_test.go
Labels: dco-signoff: yes, size/L

#41 Add DiskMappings for specific disk mappings
  deploy/crds/v2v_v1alpha1_virtualmachineimport_cr.yaml
  deploy/crds/v2v_v1alpha1_virtualmachineimport_crd.yaml
  pkg/apis/v2v/v1alpha1/resourcemapping_types.go
  pkg/apis/v2v/v1alpha1/zz_generated.deepcopy.go
  pkg/providers/ovirt/mappings/merger.go
  pkg/providers/ovirt/validation/mocks_test.go
  pkg/providers/ovirt/validation/validators/definitions.go
  pkg/providers/ovirt/validation/validators/storage-mapping-validator.go
  pkg/providers/ovirt/validation/validators/storage-mapping-validator_test.go
  pkg/providers/ovirt/validation/validators/validator-wrapper.go
  pkg/providers/ovirt/validation/vm-import-validation.go
  pkg/providers/ovirt/validation/vm-import-validation_test.go
  pkg/utils/utils.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/L

#42 Rename and start VM methods
  pkg/providers/ovirt/client/ovirt-client.go
Labels: dco-signoff: yes, release-note-none, size/M

#43 Removed RenameVM method
  pkg/apis/v2v/v1alpha1/virtualmachineimport_types.go
  pkg/providers/ovirt/client/ovirt-client.go
Labels: dco-signoff: yes, release-note-none, size/S

#44 VM status validation
  pkg/providers/ovirt/validation/validators/definitions.go
  pkg/providers/ovirt/validation/validators/vm-validator.go
  pkg/providers/ovirt/validation/validators/vm-validator_test.go
  pkg/providers/ovirt/validation/vm-import-validation.go
  pkg/providers/ovirt/validation/vm-import-validation_test.go
Labels: dco-signoff: yes, release-note-none, size/M

#46 Import failure clean-up method
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/providers/ovirt/provider.go
  pkg/providers/provider.go
Labels: dco-signoff: yes, release-note-none, size/L

#48 Added comments on public consts
  pkg/providers/provider.go
Labels: dco-signoff: yes, release-note-none, size/XS

#49 Fixed comment
  pkg/providers/ovirt/provider.go
Labels: dco-signoff: yes, release-note-none, size/XS

#50 Fixed panic on nil Annotations
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
Labels: dco-signoff: yes, release-note-none, size/XS

#47 After success method
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
Labels: dco-signoff: yes, release-note-none, size/L

#52 Secrets manager package
  pkg/secrets/secrets.go
  pkg/utils/utils.go
Labels: dco-signoff: yes, release-note-none, size/M

#53 Config maps manager
  pkg/configmaps/configmaps.go
  pkg/utils/utils.go
Labels: dco-signoff: yes, release-note-none, size/M

#54 Data Volume Secret and Config Map management refactoring
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/ovirt/mapper/mapper_test.go
  pkg/providers/ovirt/provider.go
  pkg/providers/provider.go
Labels: dco-signoff: yes, release-note-none, size/L

#56 Mapping network frontend
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/ovirt/mapper/mapper_test.go
Labels: dco-signoff: yes, release-note-none, size/M

#51 Add watching of VM and DVs
  cmd/manager/main.go
  pkg/apis/v2v/v1alpha1/virtualmachineimport_types.go
  pkg/conditions/conditions.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/ovirt/mapper/mapper_test.go
  pkg/providers/ovirt/provider.go
  pkg/utils/utils.go
Labels: dco-signoff: yes, size/XL

#55 templates: make template handling provider agnostic
  pkg/providers/ovirt/provider.go
  pkg/providers/ovirt/templates/template-finder.go
  pkg/providers/ovirt/templates/template-finder_test.go
  pkg/templates/os-mapper-provider.go
  pkg/templates/template-handler.go
  pkg/templates/template-handler_test.go
  pkg/templates/template-provider.go
  pkg/templates/templates_suite_test.go
Labels: dco-signoff: yes, release-note-none, size/XL

#58 Honoring cluster_default bios type
  pkg/providers/ovirt/client/ovirt-client.go
  pkg/providers/ovirt/validation/validators/vm-validator.go
  pkg/providers/ovirt/validation/validators/vm-validator_test.go
Labels: dco-signoff: yes, release-note-none, size/M

#60 modules: tidy dependencies
  go.sum
  vendor/golang.org/x/net/html/atom/gen.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/charmap/maketables.go
  vendor/golang.org/x/text/encoding/htmlindex/gen.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/encoding/japanese/maketables.go
  vendor/golang.org/x/text/encoding/korean/maketables.go
  vendor/golang.org/x/text/encoding/simplifiedchinese/maketables.go
  vendor/golang.org/x/text/encoding/traditionalchinese/maketables.go
  vendor/golang.org/x/text/internal/language/compact/gen.go
  vendor/golang.org/x/text/internal/language/compact/gen_index.go
  vendor/golang.org/x/text/internal/language/compact/gen_parents.go
  vendor/golang.org/x/text/internal/language/gen.go
  vendor/golang.org/x/text/internal/language/gen_common.go
  vendor/golang.org/x/text/language/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/golang.org/x/tools/go/gcexportdata/main.go
  vendor/modules.txt
Labels: dco-signoff: yes, release-note-none

#69 Nil-checks before reading Spec.StartVM
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
Labels: dco-signoff: yes, release-note-none, size/XS

#68 Gracefully re-queueing on validation failure.
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
Labels: dco-signoff: yes, release-note-none, size/M

#76 Fixing panic when source vm's id and name are missing
  pkg/providers/ovirt/client/ovirt-client.go
Labels: dco-signoff: yes, release-note-none, size/XS

#77 Reporting meaningful information about reported devices
  pkg/providers/ovirt/validation/validators/vm-validator.go
  pkg/providers/ovirt/validation/validators/vm-validator_test.go
Labels: dco-signoff: yes, release-note-none, size/M

#79 Setting Succeeded condition to 'False' status after failure
  pkg/conditions/conditions.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
Labels: dco-signoff: yes, release-note-none, size/S

#82 Set VM as owner of DV
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/ownerreferences/ownerreferences.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/L

#83 Use disk resource mappings in disk mapping
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/ovirt/mapper/mapper_test.go
Labels: dco-signoff: yes, release-note-none, size/L

#85 Stopping oVirt VM if cached VM status is not 'down'
  pkg/providers/ovirt/client/ovirt-client.go
  pkg/providers/ovirt/provider.go
Labels: dco-signoff: yes, release-note-none, size/S

#81 Ignore missing storage resource mapping
  pkg/providers/ovirt/validation/validators/definitions.go
  pkg/providers/ovirt/validation/validators/storage-mapping-validator.go
  pkg/providers/ovirt/validation/validators/storage-mapping-validator_test.go
  pkg/providers/ovirt/validation/vm-import-validation_test.go
Labels: dco-signoff: yes, release-note-none, size/L

#86 Fix nil pointer dereference in mapper
  pkg/providers/ovirt/mapper/mapper.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/M

#90 Allowing user to force default storage class
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/ovirt/mapper/mapper_test.go
  pkg/providers/ovirt/validation/validators/storage-mapping-validator.go
  pkg/providers/ovirt/validation/validators/storage-mapping-validator_test.go
Labels: dco-signoff: yes, release-note-none, size/L

#88 test: controller without reconcile
  go.mod
  pkg/controller/virtualmachineimport/controller_suite_test.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
  pkg/mappings/resource-mappings.go
Labels: dco-signoff: yes, release-note-none, size/XL

#87 Use suffixes in memory and disk size
  go.mod
  go.sum
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/ovirt/mapper/mapper_test.go
  pkg/providers/provider.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
  vendor/github.com/alecthomas/units/COPYING
  vendor/github.com/alecthomas/units/README.md
  vendor/github.com/alecthomas/units/bytes.go
  vendor/github.com/alecthomas/units/doc.go
  vendor/github.com/alecthomas/units/go.mod
  vendor/github.com/alecthomas/units/si.go
  vendor/github.com/alecthomas/units/util.go
  vendor/modules.txt
Labels: dco-signoff: yes, release-note-none, size/L

#95 Fix broken tests
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
  pkg/providers/ovirt/mapper/mapper_test.go
Labels: dco-signoff: yes, release-note-none, size/S

#96 Rename status conditions
  go.sum
  pkg/apis/v2v/v1alpha1/virtualmachineimport_types.go
  pkg/conditions/conditions.go
  pkg/conditions/conditions_test.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
  pkg/providers/ovirt/validation/vm-import-validation.go
  pkg/providers/ovirt/validation/vm-import-validation_test.go
Labels: dco-signoff: yes, release-note-none, size/L

#97 New Processing reasons
  pkg/apis/v2v/v1alpha1/virtualmachineimport_types.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
Labels: dco-signoff: yes, release-note-none, size/S

#59 Ignore if VM already exists
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
Labels: dco-signoff: yes, release-note-none, size/XS

#101 Add permissions to watch vmi
  deploy/role.yaml
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/XS

#103 Add permissions to finalizers of vm
  deploy/role.yaml
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/XS

#102 Allowing only UTC-compatible VM timezones
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/ovirt/mapper/mapper_test.go
  pkg/providers/ovirt/validation/validators/definitions.go
  pkg/providers/ovirt/validation/validators/vm-validator.go
  pkg/providers/ovirt/validation/validators/vm-validator_test.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: dco-signoff: yes, release-note-none, size/L

#104 Using vm.TimeZone.UtcOffset if available during mapping
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/ovirt/mapper/mapper_test.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: dco-signoff: yes, release-note-none, size/L

#108 Fixed DST change detection
  pkg/utils/utils.go
Labels: dco-signoff: yes, release-note-none, size/XS

#107 Fix data volume issues
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
  pkg/providers/ovirt/provider.go
  pkg/templates/template-handler.go
Labels: dco-signoff: yes, release-note-none, size/L

#109 Allow targetVmName to be optional
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/ovirt/provider.go
  pkg/providers/ovirt/templates/template-finder_test.go
  pkg/providers/provider.go
  pkg/templates/template-handler.go
  pkg/templates/template-handler_test.go
  pkg/templates/template-provider.go
Labels: dco-signoff: yes, release-note-none, size/M

#100 tests: reconcile
  go.mod
  go.sum
  pkg/client/client.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
  pkg/providers/ovirt/client/ovirt-client.go
  pkg/providers/ovirt/provider.go
Labels: dco-signoff: yes, release-note-none, size/XL

#115 naming: change import alias
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
  pkg/providers/ovirt/provider.go
Labels: dco-signoff: yes, release-note-none, size/S

#110 Add map disk interface method
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/ovirt/mapper/mapper_test.go
  pkg/providers/ovirt/provider.go
  pkg/providers/provider.go
Labels: dco-signoff: yes, release-note-none, size/L

#117 Use CDI v1.15.0
  go.mod
  go.sum
  vendor/modules.txt
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/S

#127 Log template name and template processing error
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
Labels: dco-signoff: yes, release-note-none, size/XS

#118 Generated clientset
  go.sum
  hack/boilerplate.go.txt
  hack/update-codegen.sh
  pkg/api-client/clientset/versioned/clientset.go
  pkg/api-client/clientset/versioned/doc.go
  pkg/api-client/clientset/versioned/scheme/doc.go
  pkg/api-client/clientset/versioned/scheme/register.go
  pkg/api-client/clientset/versioned/typed/v2v/v1alpha1/doc.go
  pkg/api-client/clientset/versioned/typed/v2v/v1alpha1/generated_expansion.go
  pkg/api-client/clientset/versioned/typed/v2v/v1alpha1/resourcemapping.go
  pkg/api-client/clientset/versioned/typed/v2v/v1alpha1/v2v_client.go
  pkg/api-client/clientset/versioned/typed/v2v/v1alpha1/virtualmachineimport.go
  pkg/apis/addtoscheme_v2v_v1alpha1.go
  pkg/apis/v2v/v1alpha1/register.go
  pkg/apis/v2v/v1alpha1/resourcemapping_types.go
  pkg/apis/v2v/v1alpha1/virtualmachineimport_types.go
Labels: dco-signoff: yes, release-note-none, size/XL

#113 client: connect oVirt client only when needed
  go.mod
  go.sum
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
  pkg/providers/ovirt/provider.go
  pkg/providers/provider.go
  vendor/golang.org/x/sys/unix/mkall.sh
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_netbsd.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zptrace_armnn_linux.go
  vendor/golang.org/x/sys/unix/zptrace_linux_arm64.go
  vendor/golang.org/x/sys/unix/zptrace_mipsnn_linux.go
  vendor/golang.org/x/sys/unix/zptrace_mipsnnle_linux.go
  vendor/golang.org/x/sys/unix/zptrace_x86_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_386.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_netbsd_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/ztypes_linux_386.go
  vendor/golang.org/x/sys/unix/ztypes_linux_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_arm.go
  vendor/golang.org/x/sys/unix/ztypes_linux_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips64le.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mipsle.go
  vendor/golang.org/x/sys/unix/ztypes_linux_ppc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/ztypes_linux_riscv64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_s390x.go
  vendor/golang.org/x/sys/unix/ztypes_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_netbsd_386.go
  vendor/golang.org/x/sys/unix/ztypes_netbsd_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_netbsd_arm.go
  vendor/golang.org/x/sys/unix/ztypes_netbsd_arm64.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: dco-signoff: yes, release-note-none, size/XXL

#128 Block import of VM without disks
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/providers/ovirt/validation/validators/definitions.go
  pkg/providers/ovirt/validation/validators/storage-validator.go
  pkg/providers/ovirt/validation/validators/storage-validator_test.go
  pkg/providers/ovirt/validation/vm-import-validation.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/M

#131 KubeVirt config provider
  cmd/manager/main.go
  go.sum
  pkg/config/kubevirt-config-provider.go
  pkg/config/kubevirt-config.go
  pkg/config/kubevirt-config_suite_test.go
  pkg/config/kubevirt-config_test.go
  pkg/controller/controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
  vendor/k8s.io/client-go/informers/core/v1/componentstatus.go
  vendor/k8s.io/client-go/informers/core/v1/configmap.go
  vendor/k8s.io/client-go/informers/core/v1/endpoints.go
  vendor/k8s.io/client-go/informers/core/v1/event.go
  vendor/k8s.io/client-go/informers/core/v1/interface.go
  vendor/k8s.io/client-go/informers/core/v1/limitrange.go
  vendor/k8s.io/client-go/informers/core/v1/namespace.go
  vendor/k8s.io/client-go/informers/core/v1/node.go
  vendor/k8s.io/client-go/informers/core/v1/persistentvolume.go
  vendor/k8s.io/client-go/informers/core/v1/persistentvolumeclaim.go
  vendor/k8s.io/client-go/informers/core/v1/pod.go
  vendor/k8s.io/client-go/informers/core/v1/podtemplate.go
  vendor/k8s.io/client-go/informers/core/v1/replicationcontroller.go
  vendor/k8s.io/client-go/informers/core/v1/resourcequota.go
  vendor/k8s.io/client-go/informers/core/v1/secret.go
  vendor/k8s.io/client-go/informers/core/v1/service.go
  vendor/k8s.io/client-go/informers/core/v1/serviceaccount.go
  vendor/k8s.io/client-go/informers/internalinterfaces/factory_interfaces.go
  vendor/k8s.io/client-go/listers/core/v1/componentstatus.go
  vendor/k8s.io/client-go/listers/core/v1/configmap.go
  vendor/k8s.io/client-go/listers/core/v1/endpoints.go
  vendor/k8s.io/client-go/listers/core/v1/event.go
  vendor/k8s.io/client-go/listers/core/v1/expansion_generated.go
  vendor/k8s.io/client-go/listers/core/v1/limitrange.go
  vendor/k8s.io/client-go/listers/core/v1/namespace.go
  vendor/k8s.io/client-go/listers/core/v1/node.go
  vendor/k8s.io/client-go/listers/core/v1/node_expansion.go
  vendor/k8s.io/client-go/listers/core/v1/persistentvolume.go
  vendor/k8s.io/client-go/listers/core/v1/persistentvolumeclaim.go
  vendor/k8s.io/client-go/listers/core/v1/pod.go
  vendor/k8s.io/client-go/listers/core/v1/podtemplate.go
  vendor/k8s.io/client-go/listers/core/v1/replicationcontroller.go
  vendor/k8s.io/client-go/listers/core/v1/replicationcontroller_expansion.go
  vendor/k8s.io/client-go/listers/core/v1/resourcequota.go
  vendor/k8s.io/client-go/listers/core/v1/secret.go
  vendor/k8s.io/client-go/listers/core/v1/service.go
  vendor/k8s.io/client-go/listers/core/v1/service_expansion.go
  vendor/k8s.io/client-go/listers/core/v1/serviceaccount.go
  vendor/kubevirt.io/client-go/util/util.go
  vendor/modules.txt
Labels: dco-signoff: yes, release-note-none, size/XXL

#137 templates: use vminstance namespace to process template
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
  pkg/providers/ovirt/provider.go
  pkg/providers/provider.go
  pkg/templates/template-handler.go
  pkg/templates/template-handler_test.go
Labels: dco-signoff: yes, release-note-none, size/S

#139 Add permissions for templates
  deploy/role.yaml
  pkg/providers/ovirt/templates/template-finder_test.go
  pkg/templates/template-handler.go
  pkg/templates/template-handler_test.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/S

#135 docs: add design documents
  README.md
  docs/design.md
  docs/rules.md
Labels: dco-signoff: yes, release-note-none, size/L

#134 Placement policy validation against LiveMigration KubeVirt feature gate
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/providers/ovirt/provider.go
  pkg/providers/ovirt/validation/validators/definitions.go
  pkg/providers/ovirt/validation/validators/validator-wrapper.go
  pkg/providers/ovirt/validation/validators/vm-validator.go
  pkg/providers/ovirt/validation/validators/vm-validator_test.go
  pkg/providers/ovirt/validation/vm-import-validation.go
  pkg/providers/ovirt/validation/vm-import-validation_test.go
Labels: dco-signoff: yes, release-note-none, size/L

#142 Change operator role to cluster role
  README.md
  deploy/cluster_role.yaml
  deploy/cluster_role_binding.yaml
  deploy/operator.yaml
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/S

#147 Installation steps update
  README.md
  deploy/cluster_role_binding.yaml
Labels: dco-signoff: yes, release-note, size/S

#148 Use operator namespace to find os config map
  pkg/templates/os-mapper-provider.go
Labels: dco-signoff: yes, release-note-none, size/XS

#153 Making sure that transient resources' label values are not too long
  pkg/configmaps/configmaps.go
  pkg/providers/ovirt/provider.go
  pkg/secrets/secrets.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: dco-signoff: yes, release-note, size/M

#154 Change version format to vX.Y.Z
  Makefile
  README.md
  manifests/vm-import-operator/v0.0.1/config_map.yaml
  manifests/vm-import-operator/v0.0.1/namespace.yaml
  manifests/vm-import-operator/v0.0.1/operator.yaml
  manifests/vm-import-operator/v0.0.1/v2v_v1alpha1_resourcemapping_crd.yaml
  manifests/vm-import-operator/v0.0.1/v2v_v1alpha1_virtualmachineimport_crd.yaml
  version/version.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/S

#157 Remove UpdatingSourceVM reason
  pkg/apis/v2v/v1alpha1/virtualmachineimport_types.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/XS

#155 Release v0.0.1
  manifests/vm-import-operator/v0.0.1/operator.yaml
  version/description
Labels: dco-signoff: yes, release-note-none, size/M

#27 Add tests
  .gitignore
  automation/test.sh
  cluster-sync/clean.sh
  cluster-sync/ephemeral_provider.sh
  cluster-sync/external/README.md
  cluster-sync/external/provider.sh
  cluster-sync/imageio/imageio.yaml
  cluster-sync/install.sh
  cluster-sync/k8s-1.16.2/provider.sh
  cluster-sync/nfs/nfs-sc.yaml
  cluster-sync/nfs/nfs-server.yaml
  cluster-sync/nfs/nfs-service.yaml
  cluster-sync/ocp-4.3/README.md
  cluster-sync/ocp-4.3/provider.sh
  cluster-sync/sync.sh
  cluster-up/check.sh
  cluster-up/cli.sh
  cluster-up/cluster/ephemeral-provider-common.sh
  cluster-up/cluster/external/README.md
  cluster-up/cluster/external/provider.sh
  cluster-up/cluster/images.sh
  cluster-up/cluster/k8s-1.16.2/provider.sh
  cluster-up/cluster/k8s-provider-common.sh
  cluster-up/cluster/local/README.md
  cluster-up/cluster/local/provider.sh
  cluster-up/cluster/ocp-4.3/README.md
  cluster-up/cluster/ocp-4.3/provider.sh
  cluster-up/cluster/openshift-provider-common.sh
  cluster-up/container.sh
  cluster-up/down.sh
  cluster-up/hack/common.key
  cluster-up/hack/common.sh
  cluster-up/hack/config-default.sh
  cluster-up/hack/config.sh
  cluster-up/kubeconfig.sh
  cluster-up/kubectl.sh
  cluster-up/oc.sh
  cluster-up/ssh.sh
  cluster-up/up.sh
  cluster-up/virtctl.sh
  tests/cirros/cirros.yml
  tests/cirros/mapping.yml
  tests/cirros/secret.yml
Labels: dco-signoff: yes, release-note-none, size/XXL

#158 labels: add missing labels
  pkg/providers/ovirt/provider.go
  pkg/providers/ovirt/provider_suite_test.go
  pkg/providers/ovirt/provider_test.go
  pkg/providers/ovirt/templates/template-finder.go
  pkg/templates/template-handler.go
  pkg/utils/utils.go
Labels: dco-signoff: yes, release-note-none, size/L

#162 Set reason for failed Valid condition
  pkg/apis/v2v/v1alpha1/virtualmachineimport_types.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/M

#166 Add template namespace label to the created VM
  pkg/providers/ovirt/provider_test.go
  pkg/templates/template-handler.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/S

#167 Fixing possible panic while accessing placement policy
  pkg/providers/ovirt/mapper/mapper.go
Labels: dco-signoff: yes, release-note-none, size/S

#169 Update operator resources installation
  README.md
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/S

#168 add missing labels
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/ovirt/provider.go
  pkg/providers/ovirt/provider_test.go
  pkg/providers/ovirt/templates/template-finder.go
  pkg/providers/provider.go
  pkg/templates/template-provider.go
  pkg/utils/utils.go
Labels: dco-signoff: yes, release-note-none, size/M
