Repository kubevirt/vm-import-operator, pull requests merged in 2020-06, with the labels that each got.

#268 'migratable' placement policy affinity and LiveMigration feature gate enabled test
  docs/functional-tests.md
  tests/ovirt/various_vm_configurations_test.go
Labels: dco-signoff: yes, release-note, size/M

#272 Add debugging to fail test provision infra
  cluster/common.sh
Labels: dco-signoff: yes, release-note-none, size/S

#273 Added information about resource mapping resolution and defaults for storage
  docs/design.md
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/S

#266 Install kubevirt templates for ocp tests
  cluster/common.sh
  cluster/up.sh
Labels: dco-signoff: yes, release-note-none, size/XS

#274 Set unique data-volume name
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/ovirt/mapper/mapper_test.go
  pkg/providers/provider.go
Labels: dco-signoff: yes, release-note-none, size/M

#270 Cpu pinning e2e
  docs/functional-tests.md
  tests/ovirt/stubbing/vms/cpu-pinning-template.xml
  tests/ovirt/various_vm_configurations_test.go
  tests/ovirt/vms/definitions.go
Labels: dco-signoff: yes, release-note, size/L

#271 Propagate label for tracking created resources
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
Labels: dco-signoff: yes, release-note-none, size/M

#276 Add wait-for-completion check to README
  README.md
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/S

#279 Setting Timer in a Clock during mapping
  pkg/providers/ovirt/mapper/mapper.go
Labels: dco-signoff: yes, release-note, size/XS

#277 Update func description
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/XS

#280 Release v0.0.3
  Makefile
  README.md
  manifests/vm-import-operator/v0.0.3/namespace.yaml
  manifests/vm-import-operator/v0.0.3/operator.yaml
  manifests/vm-import-operator/v0.0.3/vm-import-operator.0.0.3.clusterserviceversion.yaml
  manifests/vm-import-operator/v0.0.3/vmimportconfig_cr.yaml
  version/description
  version/version.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/L

#281 Align namespace in examples
  README.md
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/XS

#283 CPU pinning e2e test
  docs/design.md
  docs/functional-tests.md
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/ovirt/mapper/mapper_test.go
  pkg/providers/ovirt/utils/utils.go
  pkg/providers/ovirt/validation/validators/vm-validator.go
  tests/framework/node.go
  tests/ovirt/networking_test.go
  tests/ovirt/various_vm_configurations_test.go
Labels: dco-signoff: yes, release-note, size/L

#285 Remove non-cluster roles and rolebindings from cleanup logic
  pkg/operator/controller/controller.go
Labels: dco-signoff: yes, release-note-none, size/XS

#287 Refactor importDisks method
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/provider.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/L

#289 New negative test cases descriptions
  docs/functional-tests.md
Labels: dco-signoff: yes, release-note, size/S

#291 Negative import test cases
  automation/test.sh
  docs/functional-tests.md
  tests/framework/secret.go
  tests/framework/vm-import.go
  tests/matchers/vm-import.go
  tests/matchers/vmi.go
  tests/ovirt/basic_vm_import_negative_test.go
  tests/ovirt/ovirt-consts.go
  tests/ovirt/vms/definitions.go
Labels: dco-signoff: yes, release-note, size/L

#288 Check disk status before import
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
  pkg/providers/ovirt/provider.go
  pkg/providers/ovirt/validation/mocks_test.go
  pkg/providers/ovirt/validation/validators/storage-validator.go
  pkg/providers/ovirt/validation/validators/validator-wrapper.go
  pkg/providers/ovirt/validation/vm-import-validation.go
  pkg/providers/provider.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/M

#293 Functional tests for failed resource mapping validation
  docs/functional-tests.md
  tests/ovirt/resource_mapping_validation_test.go
Labels: dco-signoff: yes, release-note, size/L

#294 Updated fakeovirt API dependency
  docs/functional-tests.md
  go.mod
  go.sum
  vendor/github.com/machacekondra/fakeovirt/pkg/api/stubbing/stubbing-builder.go
  vendor/github.com/machacekondra/fakeovirt/pkg/api/stubbing/stubbing.go
  vendor/modules.txt
Labels: dco-signoff: yes, release-note, size/M

#295 Running VM import functional test
  docs/functional-tests.md
  tests/ovirt/various_vm_configurations_test.go
  tests/ovirt/vms/definitions.go
Labels: dco-signoff: yes, release-note, size/M

#296 Propagate env variables to vm-import-controller
  docs/design.md
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_test.go
  pkg/operator/resources/operator/operator.go
  vendor/kubevirt.io/containerized-data-importer/pkg/common/BUILD.bazel
  vendor/kubevirt.io/containerized-data-importer/pkg/common/common.go
  vendor/kubevirt.io/containerized-data-importer/pkg/util/BUILD.bazel
  vendor/kubevirt.io/containerized-data-importer/pkg/util/util.go
  vendor/modules.txt
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/XL

#297 New various functional test cases definitions
  docs/functional-tests.md
Labels: dco-signoff: yes, release-note, size/S

#298 Functional test for source VM that wouldn't go down
  docs/functional-tests.md
  tests/ovirt/basic_vm_import_negative_test.go
Labels: dco-signoff: yes, release-note, size/M

#299 VM import CR removal after successful import - e2e test
  docs/functional-tests.md
  tests/ovirt/basic_vm_import_test.go
Labels: dco-signoff: yes, release-note-none, size/M

#300 Sequential import of two VMs functional tests
  automation/test.sh
  docs/functional-tests.md
  go.mod
  go.sum
  tests/framework/secret.go
  tests/framework/vm-import.go
  tests/matchers/vm-import.go
  tests/ovirt/basic_vm_import_test.go
  tests/ovirt/cancel_vm_import_test.go
  tests/ovirt/multiple_vms_import_test.go
  tests/ovirt/stubbing/nics/mac-template.xml
  tests/ovirt/vms/definitions.go
  tests/utils/utils.go
  vendor/github.com/pkg/errors/.travis.yml
  vendor/github.com/pkg/errors/Makefile
  vendor/github.com/pkg/errors/README.md
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/go113.go
  vendor/github.com/pkg/errors/stack.go
  vendor/modules.txt
Labels: dco-signoff: yes, release-note-none, size/L

#303 Using pod network type as default when type is missing in the resource mapping
  docs/functional-tests.md
  pkg/providers/ovirt/mapper/mapper.go
  tests/common-vars.go
  tests/ovirt/basic_net_vm_import_test.go
  tests/ovirt/resource_mapping_validation_test.go
Labels: dco-signoff: yes, release-note-none, size/M

#304 Make sure DVs of VM import are correct
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
Labels: dco-signoff: yes, release-note-none, size/S

#305 Comment fix
  tests/common-vars.go
Labels: dco-signoff: yes, release-note-none, size/XS

#302 CNV-5368: Failing import when template is not found
  cluster/common.sh
  docs/design.md
  docs/functional-tests.md
  pkg/apis/v2v/v1alpha1/virtualmachineimport_types.go
  pkg/config/kubevirt-config.go
  pkg/config/kubevirt-config_test.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
  tests/matchers/vm-import.go
  tests/ovirt/basic_vm_import_negative_test.go
Labels: dco-signoff: yes, release-note-none, size/L

#306 Re-enabled assertion checking MAC address of the VM instance
  tests/ovirt/networking_test.go
Labels: dco-signoff: yes, release-note-none, size/XS

#308 Network resource mapping type validation hardening
  docs/design.md
  docs/functional-tests.md
  pkg/providers/ovirt/validation/validators/network-mapping-validator.go
  pkg/providers/ovirt/validation/validators/network-mapping-validator_test.go
  tests/ovirt/resource_mapping_validation_test.go
Labels: dco-signoff: yes, release-note-none, size/M

#309 Parallel import of two VMs functional test
  docs/functional-tests.md
  tests/matchers/vmi.go
  tests/ovirt/basic_vm_import_negative_test.go
  tests/ovirt/multiple_vms_import_test.go
  tests/ovirt/stubbing/disk-attachments/disk_id-template.xml
  tests/ovirt/stubbing/disk-attachments/invalid-disk.xml
  tests/ovirt/stubbing/disks/disk_id-template.xml
  tests/ovirt/stubbing/disks/invalid-disk.xml
Labels: dco-signoff: yes, release-note-none, size/L

#311 Pinning kubevirtci version
  cluster/kubevirtci.sh
Labels: dco-signoff: yes, release-note-none, size/XS

#315 Recover from oVirt client panic
  pkg/providers/ovirt/client/client_suite_test.go
  pkg/providers/ovirt/client/ovirt-client.go
  pkg/providers/ovirt/client/ovirt-client_test.go
Labels: dco-signoff: yes, release-note-none, size/M

#307 Set PVC accessMode based on source VM
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/ovirt/mapper/mapper_test.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/M

#312 Block import with more than one source network mapped to a pod network
  pkg/providers/ovirt/validation/validators/definitions.go
  pkg/providers/ovirt/validation/validators/network-mapping-validator.go
  pkg/providers/ovirt/validation/validators/network-mapping-validator_test.go
  tests/ovirt/resource_mapping_validation_test.go
Labels: dco-signoff: yes, release-note-none, size/L

#316 Allowing for VMs to have Windows-specific UTC-compatible timezones
  pkg/utils/utils.go
  pkg/utils/utils_test.go
  tests/ovirt/various_vm_configurations_test.go
Labels: dco-signoff: yes, release-note, size/S
