Repository kubevirt/vm-import-operator, pull requests merged in 2020-12, with the labels that each got.

#431 Requque when VMI not yet created
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
  tests/matchers/vm-import.go
  tests/ovirt/basic_vm_import_test.go
Labels: dco-signoff: yes, release-note-none, size/M

#442 Add documentation for Access Mode and Volume Mode
  docs/design.md
  examples/vmware/vmimport-external-mapping.yaml
  examples/vmware/vmimport-internal-mapping.yaml
Labels: dco-signoff: yes, documentation, release-note-none, size/M

#444 Pin gorilla/websocket to 1.4.2
  go.mod
  go.sum
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/XS

#445 Gracefully shutdown vSphere VMs
  pkg/providers/vmware/client/client.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/M

#450 Validate the target VM name and ensure uniqueness
  pkg/apis/v2v/v1beta1/virtualmachineimport_types.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
  tests/ovirt/multiple_vms_import_test.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/L

#447 vSphere provider should look for a small template for the given OS first
  pkg/providers/vmware/templates/template-finder.go
  pkg/providers/vmware/templates/template-finder_test.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/M

#448 Use VM UUID and disk key to name DataVolumes for vSphere VMs
  pkg/providers/vmware/mapper/mapper.go
  pkg/providers/vmware/mapper/mapper_test.go
  tests/vmware/basic_net_vm_import_test.go
  tests/vmware/basic_vm_import_test.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/S

#451 oVirt mapper: use 'scsi' bus for disks with the 'virtio_scsi' type
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/ovirt/mapper/mapper_test.go
  pkg/providers/ovirt/validation/validators/storage-validator.go
  tests/ovirt/multiple_vms_import_test.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/M

#453 Update Network Mapping validation for duplicates
  pkg/providers/ovirt/validation/validators/definitions.go
  pkg/providers/ovirt/validation/validators/network-mapping-validator.go
  pkg/providers/ovirt/validation/validators/network-mapping-validator_test.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, ok-to-test, size/M

#454 oVirt mapper should not set memory limits
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/ovirt/mapper/mapper_test.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/S

#455 Base Dockerfiles on ubi/go-toolset:1.14.12
  build/controller/Dockerfile
  build/imageio-init/Dockerfile
  build/operator/Dockerfile
  cluster/common.sh
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/M

#456 Stop Using Deprecated Packages
  cmd/manager/main.go
  cmd/operator/operator.go
  pkg/apis/v2v/v1alpha1/register.go
  pkg/apis/v2v/v1beta1/register.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_suite_test.go
Labels: dco-signoff: yes, release-note, size/S
