Repository kubevirt/vm-import-operator, pull requests merged in 2020-03, with the labels that each got.

#1 Change version to v1alpha1
  cmd/manager/main.go
  deploy/crds/v2v_v1alpha1_virtualmachineimport_cr.yaml
  deploy/crds/v2v_v1alpha1_virtualmachineimport_crd.yaml
  deploy/operator.yaml
  go.mod
  pkg/apis/addtoscheme_v2v_v1alpha1.go
  pkg/apis/v2v/v1alpha1/doc.go
  pkg/apis/v2v/v1alpha1/register.go
  pkg/apis/v2v/v1alpha1/virtualmachineimport_types.go
  pkg/apis/v2v/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/v2v/v1alpha1/zz_generated.openapi.go
  pkg/apis/v2v/v1alpha3/doc.go
  pkg/controller/add_virtualmachineimport.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
Labels: dco-signoff: yes, size/M

#2 Update VMImport custom resource
  deploy/crds/v2v_v1alpha1_virtualmachineimport_cr.yaml
  deploy/crds/v2v_v1alpha1_virtualmachineimport_crd.yaml
  examples/ovirt-mapping-example copy.yaml
  examples/ovirt-mapping-example.yaml
  examples/ovirt-secret.yaml
  go.mod
  go.sum
  pkg/apis/v2v/v1alpha1/virtualmachineimport_types.go
  pkg/apis/v2v/v1alpha1/zz_generated.deepcopy.go
Labels: dco-signoff: yes, size/L

#3 VirtualMachineImport admission hook package creation
  go.mod
  go.sum
  pkg/webhook/admission/admission_suite_test.go
  pkg/webhook/admission/vm-import-validation.go
  pkg/webhook/admission/vm-import-validation_test.go
Labels: dco-signoff: yes, size/M

#5 Add README and LICENSE
  LICENSE
  README.md
  deploy/crds/v2v_v1alpha1_virtualmachineimport_cr.yaml
Labels: dco-signoff: yes, size/L

#7 Allow specifying target VM name
  deploy/crds/v2v_v1alpha1_virtualmachineimport_cr.yaml
  examples/ovirt-mapping-example copy.yaml
  pkg/apis/v2v/v1alpha1/virtualmachineimport_types.go
  pkg/apis/v2v/v1alpha1/zz_generated.deepcopy.go
Labels: dco-signoff: yes, size/M

#6 NIC validation
  pkg/webhook/admission/utils.go
  pkg/webhook/admission/validator.go
  pkg/webhook/admission/validator_test.go
Labels: dco-signoff: yes, size/L

#4 Initial reconcile implementation
  .travis.yml
  deploy/operator.yaml
  go.mod
  go.sum
  pkg/apis/v2v/v1alpha1/virtualmachineimport_types.go
  pkg/apis/v2v/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
Labels: dco-signoff: yes, size/XXL

#8 Storage rules
  go.sum
  pkg/webhook/admission/definitions.go
  pkg/webhook/admission/nic-validator.go
  pkg/webhook/admission/nic-validator_test.go
  pkg/webhook/admission/storage-validator.go
  pkg/webhook/admission/storage-validator_test.go
  pkg/webhook/admission/vm-import-validation.go
Labels: dco-signoff: yes, size/XL

#10 VM rules
  go.sum
  pkg/webhook/admission/definitions.go
  pkg/webhook/admission/vm-import-validation.go
  pkg/webhook/admission/vm-validator.go
  pkg/webhook/admission/vm-validator_test.go
Labels: dco-signoff: yes, size/XXL

#12 Update README.md
  README.md
Labels: dco-signoff: yes, size/XS

#13 Rich oVirt client
  pkg/providers/ovirt/client/ovirt-client.go
Labels: dco-signoff: yes, size/L

#11 oVirt VM validation
  go.sum
  pkg/providers/ovirt/validation/mocks_test.go
  pkg/providers/ovirt/validation/validation_suite_test.go
  pkg/providers/ovirt/validation/validators/definitions.go
  pkg/providers/ovirt/validation/validators/nic-validator.go
  pkg/providers/ovirt/validation/validators/nic-validator_test.go
  pkg/providers/ovirt/validation/validators/storage-validator.go
  pkg/providers/ovirt/validation/validators/storage-validator_test.go
  pkg/providers/ovirt/validation/validators/utils.go
  pkg/providers/ovirt/validation/validators/validator-wrapper.go
  pkg/providers/ovirt/validation/validators/validators_suite_test.go
  pkg/providers/ovirt/validation/validators/vm-validator.go
  pkg/providers/ovirt/validation/validators/vm-validator_test.go
  pkg/providers/ovirt/validation/vm-import-validation.go
  pkg/providers/ovirt/validation/vm-import-validation_test.go
  pkg/webhook/admission/vm-import-validation.go
  pkg/webhook/admission/vm-import-validation_test.go
Labels: dco-signoff: yes, size/XXL

#9 Add ResourceMapping CRD
  README.md
  deploy/crds/v2v_v1alpha1_resourcemapping_cr.yaml
  deploy/crds/v2v_v1alpha1_resourcemapping_crd.yaml
  deploy/crds/v2v_v1alpha1_virtualmachineimport_cr.yaml
  deploy/crds/v2v_v1alpha1_virtualmachineimport_crd.yaml
  deploy/role.yaml
  examples/ovirt-mapping-example.yaml
  examples/ovirt-secret.yaml
  pkg/apis/v2v/v1alpha1/resourcemapping_types.go
  pkg/apis/v2v/v1alpha1/virtualmachineimport_types.go
  pkg/apis/v2v/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
Labels: dco-signoff: yes, size/XL

#14 Using proper condition for validation status reporting
  pkg/providers/ovirt/validation/vm-import-validation.go
  pkg/providers/ovirt/validation/vm-import-validation_test.go
Labels: dco-signoff: yes, size/M

#16 Ovirt Secret
  examples/ovirt-secret.yaml
Labels: dco-signoff: yes, size/XS

#15 Improve reconcile
  README.md
  examples/ovirt-secret.yaml
  go.mod
  go.sum
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/providers/ovirt/client/ovirt-client.go
Labels: dco-signoff: yes, size/L

#19 Validation rules fixes
  pkg/providers/ovirt/validation/validators/storage-validator.go
  pkg/providers/ovirt/validation/validators/storage-validator_test.go
  pkg/providers/ovirt/validation/validators/vm-validator.go
  pkg/providers/ovirt/validation/validators/vm-validator_test.go
Labels: dco-signoff: yes, size/M

#20 Excpect decoded CA Certificate in ovirt-secret
  README.md
  examples/ovirt-secret.yaml
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
Labels: dco-signoff: yes, size/S

#18 Network mapping validator
  go.mod
  pkg/providers/ovirt/validation/mocks_test.go
  pkg/providers/ovirt/validation/validators/definitions.go
  pkg/providers/ovirt/validation/validators/network-attachment-definition-provider.go
  pkg/providers/ovirt/validation/validators/network-mapping-validator.go
  pkg/providers/ovirt/validation/validators/network-mapping-validator_test.go
  pkg/providers/ovirt/validation/validators/nic-validator.go
  pkg/providers/ovirt/validation/validators/utils.go
  pkg/providers/ovirt/validation/validators/validator-wrapper.go
  pkg/providers/ovirt/validation/vm-import-validation.go
  pkg/providers/ovirt/validation/vm-import-validation_test.go
Labels: dco-signoff: yes, size/XL

#23 Refactor Reconcile method
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/providers/ovirt/client/ovirt-client.go
  pkg/providers/ovirt/provider.go
  pkg/providers/provider.go
Labels: dco-signoff: yes, size/XL

#22 Use validation in the reconcile loop
  go.mod
  go.sum
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/providers/ovirt/provider.go
  pkg/providers/provider.go
Labels: dco-signoff: yes, size/M

#21 Storage mapping validation
  go.mod
  go.sum
  pkg/providers/ovirt/validation/mocks_test.go
  pkg/providers/ovirt/validation/validators/definitions.go
  pkg/providers/ovirt/validation/validators/network-mapping-validator.go
  pkg/providers/ovirt/validation/validators/storage-class-provider.go
  pkg/providers/ovirt/validation/validators/storage-mapping-validator.go
  pkg/providers/ovirt/validation/validators/storage-mapping-validator_test.go
  pkg/providers/ovirt/validation/validators/utils.go
  pkg/providers/ovirt/validation/validators/validator-wrapper.go
  pkg/providers/ovirt/validation/vm-import-validation.go
  pkg/providers/ovirt/validation/vm-import-validation_test.go
Labels: dco-signoff: yes, size/L

#24 Make external resource mapping optional
  pkg/apis/v2v/v1alpha1/virtualmachineimport_types.go
  pkg/apis/v2v/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
Labels: dco-signoff: yes, size/S

#25 Retrieval and merging of resource mappings
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/mappings/resource-mappings.go
  pkg/providers/ovirt/mappings/mappings_suite_test.go
  pkg/providers/ovirt/mappings/merger.go
  pkg/providers/ovirt/mappings/merger_test.go
  pkg/providers/ovirt/provider.go
  pkg/providers/ovirt/validation/validators/network-mapping-validator.go
  pkg/providers/ovirt/validation/validators/network-mapping-validator_test.go
  pkg/providers/ovirt/validation/validators/nic-validator.go
  pkg/providers/ovirt/validation/validators/storage-mapping-validator.go
  pkg/providers/ovirt/validation/validators/storage-validator.go
  pkg/providers/provider.go
  pkg/utils/utils.go
Labels: dco-signoff: yes, size/XL

#26 Normalize VM name
  pkg/providers/ovirt/provider.go
  pkg/utils/utils.go
  pkg/utils/utils_suite_test.go
  pkg/utils/utils_test.go
Labels: dco-signoff: yes, size/L

#29 Add mapper module
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/ovirt/mapper/mapper_suite_test.go
  pkg/providers/ovirt/mapper/mapper_test.go
  pkg/providers/ovirt/provider.go
  pkg/providers/provider.go
Labels: dco-signoff: yes, size/L

#32 Fix permission of operator
  deploy/role.yaml
Labels: dco-signoff: yes, size/S

#31 Validator tests use public api
  pkg/providers/ovirt/validation/validators/network-mapping-validator.go
  pkg/providers/ovirt/validation/validators/network-mapping-validator_test.go
  pkg/providers/ovirt/validation/validators/nic-validator.go
  pkg/providers/ovirt/validation/validators/nic-validator_test.go
  pkg/providers/ovirt/validation/validators/storage-mapping-validator.go
  pkg/providers/ovirt/validation/validators/storage-mapping-validator_test.go
  pkg/providers/ovirt/validation/validators/storage-validator.go
  pkg/providers/ovirt/validation/validators/storage-validator_test.go
  pkg/providers/ovirt/validation/validators/validator-wrapper.go
  pkg/providers/ovirt/validation/validators/vm-validator.go
  pkg/providers/ovirt/validation/validators/vm-validator_test.go
Labels: dco-signoff: yes, size/L

#33 Validation tests use public API
  pkg/providers/ovirt/provider.go
  pkg/providers/ovirt/validation/mocks_test.go
  pkg/providers/ovirt/validation/vm-import-validation.go
  pkg/providers/ovirt/validation/vm-import-validation_test.go
Labels: dco-signoff: yes, size/M
