Repository kubevirt/vm-import-operator, pull requests merged in 2020-09, with the labels that each got.

#391 Update formating and depts
  go.mod
  go.sum
  pkg/mappings/merger.go
  pkg/providers/provider.go
  pkg/providers/vmware/mapper/mapper.go
  pkg/providers/vmware/mapper/mapper_test.go
  pkg/providers/vmware/os/os-finder.go
  pkg/providers/vmware/os/os-finder_test.go
  pkg/providers/vmware/templates/template-finder.go
  pkg/providers/vmware/templates/template-finder_test.go
Labels: dco-signoff: yes, release-note-none, size/S

#392 Added missing properties in the operator.yaml.in template
  templates/vm-import-operator/VERSION/operator.yaml.in
Labels: dco-signoff: yes, release-note-none, size/XS

#390 Allow specifying nodeSelector, affinity and tolerations
  pkg/apis/v2v/v1alpha1/vmimportconfig_types.go
  pkg/apis/v2v/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/v2v/v1beta1/vmimportconfig_types.go
  pkg/apis/v2v/v1beta1/zz_generated.deepcopy.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_test.go
  pkg/operator/resources/operator/operator.go
Labels: dco-signoff: yes, release-note-none, size/XL

#380 Using controller-lifecycle-operator-sdk
  go.mod
  go.sum
  pkg/apis/v2v/v1alpha1/vmimportconfig_types.go
  pkg/apis/v2v/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/v2v/v1beta1/vmimportconfig_types.go
  pkg/apis/v2v/v1beta1/zz_generated.deepcopy.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/operator/controller/callbacks.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_test.go
  pkg/operator/controller/cr-manager.go
  pkg/operator/controller/reconciler-hooks.go
  pkg/operator/resources/operator/operator.go
  pkg/utils/utils.go
  vendor/github.com/kubevirt/controller-lifecycle-operator-sdk/LICENSE
  vendor/github.com/kubevirt/controller-lifecycle-operator-sdk/pkg/sdk/api/types.go
  vendor/github.com/kubevirt/controller-lifecycle-operator-sdk/pkg/sdk/callbacks/callback-dispatcher.go
  vendor/github.com/kubevirt/controller-lifecycle-operator-sdk/pkg/sdk/cr-status.go
  vendor/github.com/kubevirt/controller-lifecycle-operator-sdk/pkg/sdk/predicate.go
  vendor/github.com/kubevirt/controller-lifecycle-operator-sdk/pkg/sdk/reconciler/builder.go
  vendor/github.com/kubevirt/controller-lifecycle-operator-sdk/pkg/sdk/reconciler/reconciler.go
  vendor/github.com/kubevirt/controller-lifecycle-operator-sdk/pkg/sdk/reconciler/versions.go
  vendor/github.com/kubevirt/controller-lifecycle-operator-sdk/pkg/sdk/resources/openapi/status.go
  vendor/github.com/kubevirt/controller-lifecycle-operator-sdk/pkg/sdk/resources/rbac.go
  vendor/github.com/kubevirt/controller-lifecycle-operator-sdk/pkg/sdk/resources/resources.go
  vendor/github.com/kubevirt/controller-lifecycle-operator-sdk/pkg/sdk/util.go
  vendor/github.com/openshift/custom-resource-status/conditions/v1/doc.go
  vendor/golang.org/x/tools/go/analysis/analysis.go
  vendor/golang.org/x/tools/go/analysis/doc.go
  vendor/golang.org/x/tools/go/ast/inspector/inspector.go
  vendor/golang.org/x/tools/go/internal/packagesdriver/sizes.go
  vendor/golang.org/x/tools/go/packages/golist.go
  vendor/golang.org/x/tools/go/packages/golist_overlay.go
  vendor/golang.org/x/tools/go/packages/loadmode_string.go
  vendor/golang.org/x/tools/go/packages/packages.go
  vendor/golang.org/x/tools/go/types/objectpath/objectpath.go
  vendor/golang.org/x/tools/imports/forward.go
  vendor/golang.org/x/tools/internal/analysisinternal/analysis.go
  vendor/golang.org/x/tools/internal/event/core/event.go
  vendor/golang.org/x/tools/internal/event/core/export.go
  vendor/golang.org/x/tools/internal/event/core/fast.go
  vendor/golang.org/x/tools/internal/event/doc.go
  vendor/golang.org/x/tools/internal/event/event.go
  vendor/golang.org/x/tools/internal/event/keys/keys.go
  vendor/golang.org/x/tools/internal/event/keys/standard.go
  vendor/golang.org/x/tools/internal/event/label/label.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk_unix.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/gocommand/vendor.go
  vendor/golang.org/x/tools/internal/gopathwalk/walk.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/imports.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/golang.org/x/tools/internal/imports/zstdlib.go
  vendor/golang.org/x/tools/internal/packagesinternal/packages.go
  vendor/golang.org/x/tools/internal/typesinternal/types.go
  vendor/modules.txt
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/XXL

#394 Release v0.2.1
  Makefile
  README.md
  manifests/vm-import-operator/v0.2.1/namespace.yaml
  manifests/vm-import-operator/v0.2.1/operator.yaml
  manifests/vm-import-operator/v0.2.1/vm-import-operator.0.2.1.clusterserviceversion.yaml
  manifests/vm-import-operator/v0.2.1/vmimportconfig_cr.yaml
  version/description
  version/version.go
Labels: dco-signoff: yes, release-note, size/L

#395 Fix HCO upgrade problem: v0.0.4->v0.2.1
  pkg/operator/resources/operator/operator.go
Labels: dco-signoff: yes, release-note-none, size/XS

#388 Add VmwareProvider
  automation/execute-tests.sh
  automation/test.sh
  cluster/manifests/vcsim.yaml.in
  cluster/vcsim-install.sh
  docs/design.md
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
  pkg/operator/resources/operator/operator.go
  pkg/providers/ovirt/provider.go
  pkg/providers/vmware/client/client.go
  pkg/providers/vmware/client/client_test.go
  pkg/providers/vmware/mapper/mapper.go
  pkg/providers/vmware/provider.go
  pkg/providers/vmware/provider_suite_test.go
  pkg/providers/vmware/provider_test.go
  pkg/utils/utils.go
  pkg/virtualmachines/virtualmachines.go
  tests/env/vmware/vmware.go
  tests/framework/framework.go
  tests/framework/secret.go
  tests/ovirt/basic_net_vm_import_test.go
  tests/ovirt/basic_vm_import_negative_test.go
  tests/ovirt/basic_vm_import_test.go
  tests/ovirt/cancel_vm_import_test.go
  tests/ovirt/multiple_disks_test.go
  tests/ovirt/multiple_vms_import_test.go
  tests/ovirt/network_validation_test.go
  tests/ovirt/networking_test.go
  tests/ovirt/resource_mapping_test.go
  tests/ovirt/resource_mapping_validation_test.go
  tests/ovirt/storage_validation_test.go
  tests/ovirt/user_provided_os_maps_migration_test.go
  tests/ovirt/various_vm_configurations_test.go
  tests/ovirt/vm_validation_test.go
  tests/utils/utils.go
  tests/vmware/basic_vm_import_negative_test.go
  tests/vmware/tests_suite_test.go
  tests/vmware/vcsim/0046-VirtualMachine-vm-57.xml
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/XXL

#396 Add virtv2v image build/push to Makefile
  Makefile
  build/virtv2v/Dockerfile
  build/virtv2v/bin/entrypoint
Labels: dco-signoff: yes, release-note-none, size/S

#397 Normalize vm hostname
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/ovirt/mapper/mapper_test.go
Labels: dco-signoff: yes, release-note-none, size/S

#398 handle cluster default bios type
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/ovirt/mapper/mapper_test.go
Labels: dco-signoff: yes, release-note-none, size/M

#399 Update template finder
  examples/config_map.yaml
  pkg/os/os-mapper-provider.go
  pkg/providers/ovirt/os/os-finder.go
  pkg/providers/ovirt/os/os-finder_test.go
  pkg/providers/ovirt/templates/template-finder_test.go
  tests/os-mapping/os-mapping.yaml
Labels: dco-signoff: yes, release-note-none, size/M

#401 Bump controller-lifecycle-operator-sdk to version 0.0.6
  go.mod
  go.sum
  vendor/github.com/kubevirt/controller-lifecycle-operator-sdk/pkg/sdk/api/types.go
  vendor/github.com/kubevirt/controller-lifecycle-operator-sdk/pkg/sdk/resources/resources.go
  vendor/modules.txt
Labels: dco-signoff: yes, release-note, size/S

#402 Improve template not found message
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
Labels: dco-signoff: yes, release-note-none, size/XS

#405 Fixing problem with changed qe-tools sum
  go.mod
  go.sum
Labels: dco-signoff: yes, release-note-none, size/XS

#406 Validate template memory requirements
  pkg/providers/ovirt/provider.go
  pkg/providers/ovirt/validation/mocks_test.go
  pkg/providers/ovirt/validation/validators/definitions.go
  pkg/providers/ovirt/validation/validators/validator-wrapper.go
  pkg/providers/ovirt/validation/validators/vm-validator.go
  pkg/providers/ovirt/validation/validators/vm-validator_test.go
  pkg/providers/ovirt/validation/vm-import-validation.go
  pkg/providers/ovirt/validation/vm-import-validation_test.go
Labels: dco-signoff: yes, release-note-none, size/L

#400 Add convertGuest step to run virt-v2v on vSphere VMs
  Makefile
  build/virtv2v/bin/entrypoint
  go.mod
  go.sum
  hack/generate-manifests.sh
  manifests/vm-import-operator/v0.2.1/operator.yaml
  manifests/vm-import-operator/v0.2.1/vm-import-operator.0.2.1.clusterserviceversion.yaml
  pkg/apis/v2v/v1alpha1/virtualmachineimport_types.go
  pkg/apis/v2v/v1beta1/virtualmachineimport_types.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
  pkg/guestconversion/guestconversion.go
  pkg/guestconversion/guestconversion_suite_test.go
  pkg/guestconversion/guestconversion_test.go
  pkg/jobs/jobs.go
  pkg/jobs/jobs_suite_test.go
  pkg/jobs/jobs_test.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_test.go
  pkg/operator/controller/cr-manager.go
  pkg/operator/resources/operator/operator.go
  pkg/ownerreferences/ownerreferences.go
  pkg/providers/ovirt/provider.go
  pkg/providers/provider.go
  pkg/providers/vmware/provider.go
  templates/vm-import-operator/VERSION/operator.yaml.in
  tests/matchers/vm-import.go
  tests/matchers/vmi.go
  tools/csv-generator/csv-generator.go
  vendor/libvirt.org/libvirt-go-xml/.gitignore
  vendor/libvirt.org/libvirt-go-xml/.gitlab-ci.yml
  vendor/libvirt.org/libvirt-go-xml/.gitmodules
  vendor/libvirt.org/libvirt-go-xml/CONTRIBUTING.rst
  vendor/libvirt.org/libvirt-go-xml/LICENSE
  vendor/libvirt.org/libvirt-go-xml/README.rst
  vendor/libvirt.org/libvirt-go-xml/capabilities.go
  vendor/libvirt.org/libvirt-go-xml/doc.go
  vendor/libvirt.org/libvirt-go-xml/document.go
  vendor/libvirt.org/libvirt-go-xml/domain.go
  vendor/libvirt.org/libvirt-go-xml/domain_capabilities.go
  vendor/libvirt.org/libvirt-go-xml/domain_snapshot.go
  vendor/libvirt.org/libvirt-go-xml/interface.go
  vendor/libvirt.org/libvirt-go-xml/network.go
  vendor/libvirt.org/libvirt-go-xml/network_port.go
  vendor/libvirt.org/libvirt-go-xml/node_device.go
  vendor/libvirt.org/libvirt-go-xml/nwfilter.go
  vendor/libvirt.org/libvirt-go-xml/nwfilter_binding.go
  vendor/libvirt.org/libvirt-go-xml/secret.go
  vendor/libvirt.org/libvirt-go-xml/storage_encryption.go
  vendor/libvirt.org/libvirt-go-xml/storage_pool.go
  vendor/libvirt.org/libvirt-go-xml/storage_vol.go
  vendor/libvirt.org/libvirt-go-xml/xmlutil.go
  vendor/modules.txt
Labels: dco-signoff: yes, release-note-none, size/XXL

#407 Release v0.2.2
  Makefile
  README.md
  manifests/vm-import-operator/v0.2.2/namespace.yaml
  manifests/vm-import-operator/v0.2.2/operator.yaml
  manifests/vm-import-operator/v0.2.2/vm-import-operator.0.2.2.clusterserviceversion.yaml
  manifests/vm-import-operator/v0.2.2/vmimportconfig_cr.yaml
  pkg/ownerreferences/ownerreferences.go
  pkg/providers/vmware/provider.go
  version/description
  version/version.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/L

#409 Update dependency
  go.mod
  go.sum
  pkg/apis/v2v/v1alpha1/vmimportconfig_types.go
  pkg/apis/v2v/v1beta1/vmimportconfig_types.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/operator/controller/callbacks.go
  pkg/operator/controller/controller.go
  pkg/operator/controller/controller_test.go
  pkg/operator/controller/cr-manager.go
  pkg/operator/resources/operator/operator.go
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/LICENSE
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/api/types.go
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/callbacks/callback-dispatcher.go
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/cr-status.go
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/predicate.go
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/reconciler/builder.go
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/reconciler/reconciler.go
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/reconciler/versions.go
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/resources/openapi/status.go
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/resources/rbac.go
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/resources/resources.go
  vendor/kubevirt.io/controller-lifecycle-operator-sdk/pkg/sdk/util.go
  vendor/modules.txt
Labels: dco-signoff: yes, release-note-none, size/M
