Repository kubevirt/vm-import-operator, pull requests merged in 2021-04, with the labels that each got.

#479 [BZ 1945121] Update storage overhead formula
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/ovirt/mapper/mapper_test.go
  pkg/providers/vmware/mapper/mapper.go
  pkg/providers/vmware/mapper/mapper_test.go
Labels: dco-signoff: yes, lgtm, release-note, size/S

#480 Release v0.3.3
  Makefile
  README.md
  manifests/vm-import-operator/v0.3.3/namespace.yaml
  manifests/vm-import-operator/v0.3.3/operator.yaml
  manifests/vm-import-operator/v0.3.3/vm-import-operator.0.3.3.clusterserviceversion.yaml
  manifests/vm-import-operator/v0.3.3/vmimportconfig_cr.yaml
  version/description
  version/version.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/L

#482 Requeue while waiting for disk copies and guest conversion to complete
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/S

#481 Use IsDNS1123Label to validate VM names
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/XS

#483 Start VMs so WaitForFirstConsumer DVs can bind
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
  pkg/controller/virtualmachineimport/warmimport.go
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/provider.go
  pkg/providers/vmware/mapper/mapper.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/M

#485 Validate that vSphere networks are mapped
  pkg/apis/v2v/v1beta1/resourcemapping_types.go
  pkg/providers/vmware/mapper/mapper.go
  pkg/providers/vmware/provider.go
  pkg/providers/vmware/provider_test.go
  tests/vmware/basic_vm_import_negative_test.go
  tests/vmware/basic_vm_import_test.go
  tests/vmware/basic_vm_warm_import_test.go
  tests/vmware/cancel_vm_import_test.go
  tests/vmware/definitions.go
  tests/vmware/resource_mapping_test.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/L

#486 Release v0.3.4
  Makefile
  README.md
  manifests/vm-import-operator/v0.3.4/namespace.yaml
  manifests/vm-import-operator/v0.3.4/operator.yaml
  manifests/vm-import-operator/v0.3.4/vm-import-operator.0.3.4.clusterserviceversion.yaml
  manifests/vm-import-operator/v0.3.4/vmimportconfig_cr.yaml
  version/description
  version/version.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/L
