Repository kubevirt/vm-import-operator, pull requests merged in 2021-09, with the labels that each got.

#510 Remove ovirt timezone validation
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/ovirt/mapper/mapper_test.go
  pkg/providers/ovirt/validation/validators/vm-validator.go
  pkg/providers/ovirt/validation/validators/vm-validator_test.go
Labels: dco-signoff: yes, size/M, do-not-merge/release-note-label-needed

#509 Use sha1 for oVirt DV names to avoid truncating
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
  pkg/controller/virtualmachineimport/warmimport.go
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/ovirt/mapper/mapper_test.go
  pkg/providers/ovirt/provider.go
  pkg/providers/provider.go
  pkg/providers/vmware/provider.go
Labels: dco-signoff: yes, size/M, do-not-merge/release-note-label-needed

#511 Apply overhead after rounding to next 1M.
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/ovirt/mapper/mapper_test.go
  pkg/providers/vmware/mapper/mapper.go
  pkg/providers/vmware/mapper/mapper_test.go
Labels: dco-signoff: yes, size/S, release-note-none

#514 Remove trailing slash in tools.go
  tools.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XS, release-note-none

#513 Update e2e tests to use k8s-1.20 to fix CI issues.
  cluster/kubevirtci.sh
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/ovirt/mapper/mapper_test.go
  tests/ovirt/basic_net_vm_import_test.go
  tests/ovirt/basic_vm_import_negative_test.go
  tests/ovirt/basic_vm_import_test.go
  tests/ovirt/various_vm_configurations_test.go
  tests/ovirt/vm_validation_test.go
Labels: dco-signoff: yes, size/S, do-not-merge/release-note-label-needed

#515 Fix failure to clean up after warm migration
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/XS
