Repository kubevirt/vm-import-operator, pull requests merged in 2021-01, with the labels that each got.

#463 Fix failing schema validation test
  pkg/operator/resources/operator/operator_test.go
Labels: dco-signoff: yes, release-note-none, size/XS

#461 Improve DataVolume importer CrashLoopBackoff message
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/S

#462 Run `make fmt` to fix accumulated lint
  cmd/operator/operator.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/warmimport.go
  pkg/operator/controller/controller.go
  pkg/providers/ovirt/mapper/mapper_test.go
  pkg/providers/ovirt/validation/validators/storage-validator.go
  pkg/providers/vmware/templates/template-finder.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/runtime/scheme/scheme.go
  vendor/sigs.k8s.io/controller-runtime/pkg/runtime/signals/signal.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/M

#465 Fail import when V2V overlays can't be committed.
  build/virtv2v/bin/entrypoint
Labels: dco-signoff: yes, needs-ok-to-test, release-note, size/S

#466 Skip the job and directly create a pod for guest conversion
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
  pkg/guestconversion/guestconversion.go
  pkg/guestconversion/guestconversion_test.go
  pkg/jobs/jobs.go
  pkg/operator/resources/operator/operator.go
  pkg/pods/pods.go
  pkg/pods/pods_suite_test.go
  pkg/pods/pods_test.go
  pkg/providers/ovirt/provider.go
  pkg/providers/provider.go
  pkg/providers/vmware/provider.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/XL

#464 Mount block devices properly on the virt-v2v container
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller_test.go
  pkg/guestconversion/guestconversion.go
  pkg/guestconversion/guestconversion_test.go
  pkg/providers/ovirt/provider.go
  pkg/providers/provider.go
  pkg/providers/vmware/provider.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/L

#467 vSphere: remove any default networks and interfaces from VM template
  pkg/providers/vmware/mapper/mapper.go
  pkg/providers/vmware/mapper/mapper_test.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/M

#468 Fail the import if the target VM can't be found
  pkg/apis/v2v/v1beta1/virtualmachineimport_types.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/controller/virtualmachineimport/warmimport.go
  pkg/providers/ovirt/provider.go
  pkg/providers/vmware/provider.go
  tests/framework/vm-import.go
  tests/ovirt/deleted_vm_import_test.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/L
