Repository kubevirt/vm-import-operator, pull requests merged in 2021-03, with the labels that each got.

#470 Add validation that VMWare Tools are present
  cluster/manifests/vcsim.yaml.in
  pkg/providers/vmware/provider.go
  pkg/providers/vmware/provider_test.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, ok-to-test, size/L

#476 Pull centos:8 from Quay.io
  build/virtv2v/Dockerfile
Labels: dco-signoff: yes, release-note-none, size/XS

#475 Release v0.3.1
  Makefile
  README.md
  manifests/vm-import-operator/v0.3.1/namespace.yaml
  manifests/vm-import-operator/v0.3.1/operator.yaml
  manifests/vm-import-operator/v0.3.1/vm-import-operator.0.3.1.clusterserviceversion.yaml
  manifests/vm-import-operator/v0.3.1/vmimportconfig_cr.yaml
  version/description
  version/version.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/L

#477 Fix warm import status update
  pkg/controller/virtualmachineimport/warmimport.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/XS

#478 Release v0.3.2
  Makefile
  README.md
  manifests/vm-import-operator/v0.3.2/namespace.yaml
  manifests/vm-import-operator/v0.3.2/operator.yaml
  manifests/vm-import-operator/v0.3.2/vm-import-operator.0.3.2.clusterserviceversion.yaml
  manifests/vm-import-operator/v0.3.2/vmimportconfig_cr.yaml
  version/description
  version/version.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/L
