Repository kubevirt/vm-import-operator, pull requests merged in 2021-08, with the labels that each got.

#502 README: improve the README
  README.md
Labels: dco-signoff: yes, size/S, do-not-merge/release-note-label-needed, needs-ok-to-test

#504 Remove dependency on obsolete Kubevirt config map
  docs/rules.md
  pkg/config/controller/config.go
  pkg/config/kubevirt/config.go
  pkg/config/kubevirt/config_test.go
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
  pkg/providers/ovirt/validation/validators/vm-validator.go
  pkg/providers/ovirt/validation/validators/vm-validator_test.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/L

#506 Release v0.4.0
  Makefile
  README.md
  hack/bump-version.sh
  manifests/vm-import-operator/v0.4.0/namespace.yaml
  manifests/vm-import-operator/v0.4.0/operator.yaml
  manifests/vm-import-operator/v0.4.0/vm-import-operator.0.4.0.clusterserviceversion.yaml
  manifests/vm-import-operator/v0.4.0/vmimportconfig_cr.yaml
  version/description
  version/version.go
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, size/L

#507 Remove redundant condition check from shouldStartVm
  pkg/controller/virtualmachineimport/virtualmachineimport_controller.go
Labels: dco-signoff: yes, size/XS, release-note-none

#508 Round disk size to 1Mi, instead of 512 bytes
  go.sum
  pkg/providers/ovirt/mapper/mapper.go
  pkg/providers/ovirt/mapper/mapper_test.go
  pkg/providers/vmware/mapper/mapper.go
  pkg/providers/vmware/mapper/mapper_test.go
Labels: dco-signoff: yes, size/S, release-note-none
